/** 按《西游记》回目展开的关卡表。1–5 关为开篇至学艺，自第003回起一回一关。 */

export type StageDef = {
  chapter: number
  name: string
  breakTitle: string
  /** -1 = 五彩石 */
  hero: number
  /** -1 = 五行精灵；数组则按敌人 kind 轮换 */
  enemy: number | readonly number[]
  bolt: number
  road: number
  burst: string
  boltVz: number
  boltElem: number
}

export const STAGE_DEFS: readonly StageDef[] = [
  {
    chapter: 1,
    name: '补天五彩石',
    breakTitle: '石破天惊 · 灵猴出世',
    hero: -1,
    enemy: -1,
    bolt: 0,
    road: 0,
    burst: '#ffd647',
    boltVz: 18,
    boltElem: 4,
  },
  {
    chapter: 1,
    name: '花果山小灵猴',
    breakTitle: '水帘洞天 · 洞府自成',
    hero: 0,
    enemy: 0,
    bolt: 0,
    road: 1,
    burst: '#c8a070',
    boltVz: 18,
    boltElem: 4,
  },
  {
    chapter: 1,
    name: '出海寻仙',
    breakTitle: '乘槎破浪 · 方寸在望',
    hero: 1,
    enemy: 1,
    bolt: 1,
    road: 2,
    burst: '#7ad4ff',
    boltVz: 24,
    boltElem: 2,
  },
  {
    chapter: 2,
    name: '方寸山外门',
    breakTitle: '粗布换霞 · 道袍将成',
    hero: 2,
    enemy: 2,
    bolt: 2,
    road: 3,
    burst: '#8a5a28',
    boltVz: 20,
    boltElem: 1,
  },
  {
    chapter: 2,
    name: '方寸山问道',
    breakTitle: '金身问道 · 学成出师',
    hero: 3,
    enemy: 3,
    bolt: 3,
    road: 4,
    burst: '#ff6a22',
    boltVz: 22,
    boltElem: 3,
  },
  {
    chapter: 3,
    name: '龙宫借宝',
    breakTitle: '定海神珍 · 勾销死籍',
    hero: 4,
    enemy: [4, 5],
    bolt: 4,
    road: 5,
    burst: '#ffe56a',
    boltVz: 26,
    boltElem: 0,
  },
  {
    chapter: 4,
    name: '弼马温',
    breakTitle: '官封弼马 · 名注齐天',
    hero: 5,
    enemy: 6,
    bolt: 4,
    road: 6,
    burst: '#ffd24a',
    boltVz: 24,
    boltElem: 0,
  },
  {
    chapter: 5,
    name: '乱蟠桃',
    breakTitle: '偷丹乱会 · 反下天宫',
    hero: 6,
    enemy: 7,
    bolt: 5,
    road: 7,
    burst: '#ff8ab0',
    boltVz: 22,
    boltElem: 3,
  },
  {
    chapter: 6,
    name: '二郎降',
    breakTitle: '小圣施威 · 天罗地网',
    hero: 7,
    enemy: [8, 9],
    bolt: 4,
    road: 8,
    burst: '#c9e6ff',
    boltVz: 26,
    boltElem: 0,
  },
  {
    chapter: 7,
    name: '八卦炉',
    breakTitle: '火眼金睛 · 五行山定',
    hero: 8,
    enemy: 10,
    bolt: 6,
    road: 9,
    burst: '#ff6a22',
    boltVz: 24,
    boltElem: 3,
  },
  {
    chapter: 8,
    name: '灵山传经',
    breakTitle: '我佛造经 · 观音东去',
    hero: 9,
    enemy: 11,
    bolt: 7,
    road: 10,
    burst: '#ffe9a0',
    boltVz: 22,
    boltElem: 0,
  },
  {
    chapter: 9,
    name: '泾河犯天',
    breakTitle: '妙算无私 · 老龙犯条',
    hero: 9,
    enemy: 12,
    bolt: 1,
    road: 11,
    burst: '#47b8ff',
    boltVz: 23,
    boltElem: 2,
  },
  {
    chapter: 10,
    name: '地府还魂',
    breakTitle: '宫门镇鬼 · 太宗还魂',
    hero: 9,
    enemy: 13,
    bolt: 8,
    road: 12,
    burst: '#7dffc4',
    boltVz: 21,
    boltElem: 2,
  },
  {
    chapter: 11,
    name: '六道轮回',
    breakTitle: '遵善果 · 度孤魂',
    hero: 9,
    enemy: 14,
    bolt: 8,
    road: 13,
    burst: '#9ad0ff',
    boltVz: 21,
    boltElem: 4,
  },
  {
    chapter: 12,
    name: '水陆大会',
    breakTitle: '秉诚建会 · 金蝉现身',
    hero: 9,
    enemy: 15,
    bolt: 7,
    road: 14,
    burst: '#ffd24a',
    boltVz: 22,
    boltElem: 0,
  },
  {
    chapter: 13,
    name: '双叉岭',
    breakTitle: '陷虎穴 · 伯钦留僧',
    hero: 9,
    enemy: 16,
    bolt: 4,
    road: 15,
    burst: '#e07a3a',
    boltVz: 24,
    boltElem: 4,
  },
  {
    chapter: 14,
    name: '心猿归正',
    breakTitle: '揭帖出山 · 六贼无踪',
    hero: 10,
    enemy: 17,
    bolt: 4,
    road: 16,
    burst: '#ffe56a',
    boltVz: 26,
    boltElem: 0,
  },
  {
    chapter: 15,
    name: '鹰愁涧',
    breakTitle: '诸神暗佑 · 意马收缰',
    hero: 10,
    enemy: 18,
    bolt: 1,
    road: 17,
    burst: '#9be7ff',
    boltVz: 24,
    boltElem: 2,
  },
  {
    chapter: 16,
    name: '观音院',
    breakTitle: '僧谋宝贝 · 袈裟被窃',
    hero: 10,
    enemy: 19,
    bolt: 4,
    road: 18,
    burst: '#ffb24a',
    boltVz: 24,
    boltElem: 0,
  },
  {
    chapter: 17,
    name: '黑风山',
    breakTitle: '大闹黑风 · 菩萨收熊',
    hero: 10,
    enemy: 20,
    bolt: 9,
    road: 19,
    burst: '#7a6cff',
    boltVz: 25,
    boltElem: 4,
  },
  {
    chapter: 18,
    name: '高老庄',
    breakTitle: '唐僧脱难 · 行者降魔',
    hero: 10,
    enemy: 21,
    bolt: 4,
    road: 20,
    burst: '#e8a070',
    boltVz: 24,
    boltElem: 0,
  },
  {
    chapter: 19,
    name: '云栈洞',
    breakTitle: '收伏八戒 · 浮屠心经',
    hero: 10,
    enemy: 22,
    bolt: 4,
    road: 21,
    burst: '#d4a0ff',
    boltVz: 25,
    boltElem: 0,
  },
  {
    chapter: 20,
    name: '黄风岭',
    breakTitle: '唐僧有难 · 八戒争先',
    hero: 10,
    enemy: [24, 23],
    bolt: 10,
    road: 22,
    burst: '#e6c14a',
    boltVz: 23,
    boltElem: 4,
  },
  {
    chapter: 21,
    name: '定风魔',
    breakTitle: '护法留庄 · 灵吉定风',
    hero: 10,
    enemy: 23,
    bolt: 10,
    road: 24,
    burst: '#ffe56a',
    boltVz: 24,
    boltElem: 0,
  },
  {
    chapter: 22,
    name: '流沙河',
    breakTitle: '八戒大战 · 木叉收净',
    hero: 10,
    enemy: 25,
    bolt: 1,
    road: 23,
    burst: '#c4a46a',
    boltVz: 22,
    boltElem: 2,
  },
  {
    chapter: 23,
    name: '四圣试禅',
    breakTitle: '三藏不忘本 · 四圣试禅心',
    hero: 10,
    enemy: 26,
    bolt: 7,
    road: 25,
    burst: '#ffb6d9',
    boltVz: 22,
    boltElem: 1,
  },
  {
    chapter: 24,
    name: '五庄观',
    breakTitle: '大仙留友 · 行者窃果',
    hero: 10,
    enemy: 27,
    bolt: 11,
    road: 26,
    burst: '#7dff9a',
    boltVz: 21,
    boltElem: 1,
  },
  {
    chapter: 25,
    name: '镇元仙',
    breakTitle: '赶捉取经僧 · 大闹五庄',
    hero: 10,
    enemy: [28, 27],
    bolt: 4,
    road: 27,
    burst: '#5ad48a',
    boltVz: 25,
    boltElem: 0,
  },
  {
    chapter: 26,
    name: '三岛求方',
    breakTitle: '海外求方 · 甘泉活树',
    hero: 10,
    enemy: 29,
    bolt: 7,
    road: 28,
    burst: '#9be7ff',
    boltVz: 23,
    boltElem: 2,
  },
  {
    chapter: 27,
    name: '白虎岭',
    breakTitle: '尸魔三戏 · 圣僧恨逐',
    hero: 10,
    enemy: 30,
    bolt: 12,
    road: 29,
    burst: '#e8e0d0',
    boltVz: 24,
    boltElem: 4,
  },
  {
    chapter: 28,
    name: '群妖聚义',
    breakTitle: '花果聚义 · 黑松逢魔',
    hero: 10,
    enemy: 31,
    bolt: 4,
    road: 30,
    burst: '#c8a070',
    boltVz: 25,
    boltElem: 0,
  },
  {
    chapter: 29,
    name: '宝象国',
    breakTitle: '脱难来国 · 八戒转林',
    hero: 10,
    enemy: 32,
    bolt: 4,
    road: 31,
    burst: '#f0d48a',
    boltVz: 23,
    boltElem: 0,
  },
  {
    chapter: 30,
    name: '黄袍怪',
    breakTitle: '邪魔侵正 · 意马忆猿',
    hero: 10,
    enemy: 33,
    bolt: 4,
    road: 32,
    burst: '#e6c14a',
    boltVz: 24,
    boltElem: 0,
  },
  {
    chapter: 31,
    name: '智降黄袍',
    breakTitle: '八戒义激 · 行者智降',
    hero: 10,
    enemy: 33,
    bolt: 4,
    road: 31,
    burst: '#ffd24a',
    boltVz: 26,
    boltElem: 0,
  },
  {
    chapter: 32,
    name: '平顶山',
    breakTitle: '功曹传信 · 木母逢灾',
    hero: 10,
    enemy: 34,
    bolt: 4,
    road: 33,
    burst: '#d4a070',
    boltVz: 24,
    boltElem: 0,
  },
  {
    chapter: 33,
    name: '莲花洞',
    breakTitle: '外道迷真 · 元神助本',
    hero: 10,
    enemy: [35, 34],
    bolt: 13,
    road: 34,
    burst: '#c070ff',
    boltVz: 22,
    boltElem: 0,
  },
  {
    chapter: 34,
    name: '金角大王',
    breakTitle: '魔王巧算 · 大圣骗宝',
    hero: 10,
    enemy: 35,
    bolt: 13,
    road: 34,
    burst: '#ffb24a',
    boltVz: 24,
    boltElem: 0,
  },
  {
    chapter: 35,
    name: '银角大王',
    breakTitle: '外道施威 · 心猿获宝',
    hero: 10,
    enemy: 36,
    bolt: 13,
    road: 34,
    burst: '#c9e6ff',
    boltVz: 25,
    boltElem: 0,
  },
  {
    chapter: 36,
    name: '见月明',
    breakTitle: '诸缘伏 · 旁门见月',
    hero: 10,
    enemy: 15,
    bolt: 7,
    road: 35,
    burst: '#d0e8ff',
    boltVz: 22,
    boltElem: 0,
  },
  {
    chapter: 37,
    name: '乌鸡国',
    breakTitle: '鬼王夜谒 · 神化引婴',
    hero: 10,
    enemy: 37,
    bolt: 8,
    road: 36,
    burst: '#7dffc4',
    boltVz: 21,
    boltElem: 2,
  },
  {
    chapter: 38,
    name: '辨假真',
    breakTitle: '问母知邪 · 金木参玄',
    hero: 10,
    enemy: 38,
    bolt: 4,
    road: 36,
    burst: '#c4e070',
    boltVz: 24,
    boltElem: 0,
  },
  {
    chapter: 39,
    name: '金丹救主',
    breakTitle: '天上金丹 · 故主还阳',
    hero: 10,
    enemy: 38,
    bolt: 5,
    road: 36,
    burst: '#ffd24a',
    boltVz: 22,
    boltElem: 3,
  },
  {
    chapter: 40,
    name: '火云洞',
    breakTitle: '婴儿戏化 · 禅心大乱',
    hero: 10,
    enemy: 39,
    bolt: 14,
    road: 37,
    burst: '#ff4a22',
    boltVz: 26,
    boltElem: 3,
  },
  {
    chapter: 41,
    name: '圣婴大火',
    breakTitle: '心猿遭火 · 木母被擒',
    hero: 10,
    enemy: 39,
    bolt: 14,
    road: 37,
    burst: '#ff6a22',
    boltVz: 26,
    boltElem: 3,
  },
  {
    chapter: 42,
    name: '南海收婴',
    breakTitle: '大圣拜海 · 观音缚孩',
    hero: 10,
    enemy: 11,
    bolt: 7,
    road: 38,
    burst: '#9be7ff',
    boltVz: 23,
    boltElem: 2,
  },
]

export const STAGE_COUNT = STAGE_DEFS.length
export const STAGE_NAMES = STAGE_DEFS.map((s) => s.name)
export const BREAK_TITLES = STAGE_DEFS.map((s) => s.breakTitle)

export function stageDef(stage: number): StageDef {
  const i = Math.max(0, Math.min(STAGE_DEFS.length - 1, stage - 1))
  const d = STAGE_DEFS[i]
  return { ...d, hero: i === 0 ? -1 : i - 1 }
}

/** Stage 1 uses the stone; later stages use wukong_s{N}.png (hero index N-2). */
export function heroIndexForStage(stage: number): number {
  if (stage <= 1) return -1
  return Math.min(STAGE_DEFS.length - 2, stage - 2)
}
