export type WorldGenre = 'HISTORY' | 'CLASSICS' | 'DRAMA' | 'NOVEL' | 'CUSTOM'

export type Skill = { name: string; description: string }

export type WorldPreset = {
  id: string
  worldId: string
  name: string
  lore: string
  skills: Skill[]
  grade: string
  roleHint: string
  faction: string
  nickname: string
  fullLore: string
}

export type SmallWorld = {
  id: string
  title: string
  genre: WorldGenre
  sourceHint: string
  lore: string
  fullLore: string
  canonHint: string
  coverKey: 'classics' | 'history' | 'drama' | 'novel' | 'xiyou' | 'sanguo' | 'shuihu' | 'liaozhai'
  official: boolean
  presets: WorldPreset[]
}

export const GENRE_LABEL: Record<WorldGenre, string> = {
  HISTORY: '历史国度',
  CLASSICS: '四大名著',
  DRAMA: '著名剧集',
  NOVEL: '热门小说',
  CUSTOM: '自定义',
}

export const COVER: Record<SmallWorld['coverKey'], string> = {
  classics: '/art/cover_classics.png',
  history: '/art/cover_history.png',
  drama: '/art/cover_drama.png',
  novel: '/art/cover_novel.png',
  xiyou: '/art/cover_xiyou.png',
  sanguo: '/art/cover_sanguo.png',
  shuihu: '/art/cover_shuihu.png',
  liaozhai: '/art/cover_liaozhai.png',
}

export const officialWorlds: SmallWorld[] = [
  {
    id: "w_xiyou",
    title: "西游记",
    genre: "CLASSICS",
    sourceHint: "吴承恩",
    lore: "西天取经路，八十一难精怪拦道",
    fullLore: "唐僧奉旨西行求取真经，收悟空、八戒、沙僧与白龙马为伴。沿途有天庭仙佛点拨，也有洞府精怪劫僧。战场是取经路：山岭、流沙、火焰山与西天雷音之间的试炼。神通可变可战，但须受金箍、因果与佛门约束，不得写成无敌不死。",
    canonHint: "神通、金箍、变化、禅机；禁无敌不死与热兵器",
    coverKey: "xiyou",
    official: true,
    presets: [
      {
        id: "w_xiyou_tangseng",
        worldId: "w_xiyou",
        name: "唐僧",
        nickname: "三藏",
        faction: "取经行",
        lore: "西行求经的慈悲僧侣",
        fullLore: "金蝉子转世，奉旨西行。性格慈悲却易误信，金箍约束悟空。卡面强调梵音、戒律与求经意志，不写不死金身。",
        grade: "SSR",
        roleHint: "师傅",
        skills: [{ name: "唐僧", description: "以梵音稳住心神" }, { name: "紧箍", description: "约束己方过猛攻势" }, { name: "慈悲", description: "暂缓敌方杀意" }],
      },
      {
        id: "w_xiyou_wukong",
        worldId: "w_xiyou",
        name: "孙悟空",
        nickname: "齐天大圣",
        faction: "取经行",
        lore: "花果山石猴出身的先锋",
        fullLore: "灵石孕育，学七十二变，金箍棒可大可小。大闹天宫后受金箍，专克精怪。技能写变化与识破，不写无敌不死。",
        grade: "SSR",
        roleHint: "大师兄",
        skills: [{ name: "棒影", description: "迅捷砸开防线" }, { name: "变化", description: "错位躲开一击" }, { name: "火眼", description: "看破幻形伪装" }],
      },
      {
        id: "w_xiyou_bajie",
        worldId: "w_xiyou",
        name: "猪八戒",
        nickname: "天蓬元帅",
        faction: "取经行",
        lore: "贪嘴却敢挡灾的二师兄",
        fullLore: "贪嘴却敢挡灾的二师兄",
        grade: "SR",
        roleHint: "二师兄",
        skills: [{ name: "钉耙", description: "横扫近身敌人" }, { name: "变猪", description: "以笨拙诱敌露破绽" }, { name: "拱撞", description: "短距冲开人群" }],
      },
      {
        id: "w_xiyou_sha",
        worldId: "w_xiyou",
        name: "沙和尚",
        nickname: "卷帘大将",
        faction: "取经行",
        lore: "挑担护僧的稳重三师兄",
        fullLore: "挑担护僧的稳重三师兄",
        grade: "SR",
        roleHint: "三师兄",
        skills: [{ name: "宝杖", description: "格挡一次冲击" }, { name: "流沙", description: "迟滞对手脚步" }, { name: "担经", description: "稳住己方阵脚" }],
      },
      {
        id: "w_xiyou_bailong",
        worldId: "w_xiyou",
        name: "白龙马",
        nickname: "西海三太子",
        faction: "取经行",
        lore: "化马驮僧的龙族少年",
        fullLore: "化马驮僧的龙族少年",
        grade: "SR",
        roleHint: "坐骑",
        skills: [{ name: "龙吟", description: "震慑动摇敌心" }, { name: "踏浪", description: "拉开交锋距离" }, { name: "化鳞", description: "短暂抵御火势" }],
      },
      {
        id: "w_xiyou_guanyin",
        worldId: "w_xiyou",
        name: "观音",
        nickname: "落伽尊者",
        faction: "仙佛",
        lore: "点化取经人的慈悲菩萨",
        fullLore: "点化取经人的慈悲菩萨",
        grade: "SSR",
        roleHint: "指引",
        skills: [{ name: "净瓶", description: "化解一场灼烧" }, { name: "杨枝", description: "点破一门路径" }, { name: "收伏", description: "暂时缚住精怪" }],
      },
      {
        id: "w_xiyou_rulai",
        worldId: "w_xiyou",
        name: "如来",
        nickname: "佛祖",
        faction: "仙佛",
        lore: "西天雷音的最终试炼者",
        fullLore: "西天雷音的最终试炼者",
        grade: "SSR",
        roleHint: "终局",
        skills: [{ name: "掌印", description: "压住过猛攻势" }, { name: "真经", description: "强化取经意志" }, { name: "因果", description: "反弹一次咒术" }],
      },
      {
        id: "w_xiyou_yuhuang",
        worldId: "w_xiyou",
        name: "玉帝",
        nickname: "昊天",
        faction: "仙佛",
        lore: "天庭秩序的守持者",
        fullLore: "天庭秩序的守持者",
        grade: "SR",
        roleHint: "天庭",
        skills: [{ name: "天条", description: "迟滞对手行动" }, { name: "宣召", description: "唤来短暂援势" }],
      },
      {
        id: "w_xiyou_laojun",
        worldId: "w_xiyou",
        name: "太上老君",
        nickname: "道德天尊",
        faction: "仙佛",
        lore: "炼丹炉火的清静道祖",
        fullLore: "炼丹炉火的清静道祖",
        grade: "SR",
        roleHint: "道门",
        skills: [{ name: "炉火", description: "灼烧前方区域" }, { name: "金钢琢", description: "打断对手咏唱" }],
      },
      {
        id: "w_xiyou_taibai",
        worldId: "w_xiyou",
        name: "太白金星",
        nickname: "李长庚",
        faction: "仙佛",
        lore: "劝和招安的天庭说客",
        fullLore: "劝和招安的天庭说客",
        grade: "R",
        roleHint: "说客",
        skills: [{ name: "劝降", description: "动摇敌方心神" }, { name: "招安", description: "暂缓一场冲突" }],
      },
      {
        id: "w_xiyou_erlang",
        worldId: "w_xiyou",
        name: "杨戬",
        nickname: "二郎神",
        faction: "仙佛",
        lore: "三只眼的天庭战将",
        fullLore: "三只眼的天庭战将",
        grade: "SSR",
        roleHint: "战神",
        skills: [{ name: "天眼", description: "看破潜藏杀机" }, { name: "三尖刀", description: "劈开一道防线" }, { name: "哮天", description: "追击逃开的敌人" }],
      },
      {
        id: "w_xiyou_nezha",
        worldId: "w_xiyou",
        name: "哪吒",
        nickname: "三太子",
        faction: "仙佛",
        lore: "莲身火枪的少年神将",
        fullLore: "莲身火枪的少年神将",
        grade: "SR",
        roleHint: "神将",
        skills: [{ name: "火尖枪", description: "突袭打断施法" }, { name: "风火轮", description: "迅捷绕到侧翼" }],
      },
      {
        id: "w_xiyou_lita",
        worldId: "w_xiyou",
        name: "李靖",
        nickname: "托塔天王",
        faction: "仙佛",
        lore: "镇守天门的托塔父帅",
        fullLore: "镇守天门的托塔父帅",
        grade: "R",
        roleHint: "天将",
        skills: [{ name: "宝塔", description: "短暂困住对手" }, { name: "点将", description: "整军强化一回合" }],
      },
      {
        id: "w_xiyou_zhenyuan",
        worldId: "w_xiyou",
        name: "镇元子",
        nickname: "地仙之祖",
        faction: "仙佛",
        lore: "五庄观人参果的主人",
        fullLore: "五庄观人参果的主人",
        grade: "SR",
        roleHint: "地仙",
        skills: [{ name: "人参果", description: "调息稳住己方" }, { name: "袖里乾坤", description: "错位拉开距离" }],
      },
      {
        id: "w_xiyou_mile",
        worldId: "w_xiyou",
        name: "弥勒",
        nickname: "未来佛",
        faction: "仙佛",
        lore: "袋中乾坤的笑面佛",
        fullLore: "袋中乾坤的笑面佛",
        grade: "SR",
        roleHint: "佛门",
        skills: [{ name: "布袋", description: "收走一场攻势" }, { name: "笑颜", description: "扰乱对手判断" }],
      },
      {
        id: "w_xiyou_lingji",
        worldId: "w_xiyou",
        name: "灵吉菩萨",
        nickname: "须弥尊者",
        faction: "仙佛",
        lore: "克制黄风的菩萨",
        fullLore: "克制黄风的菩萨",
        grade: "R",
        roleHint: "克制",
        skills: [{ name: "定风珠", description: "压住狂风扰乱" }],
      },
      {
        id: "w_xiyou_baigujing",
        worldId: "w_xiyou",
        name: "白骨精",
        nickname: "白骨夫人",
        faction: "精怪",
        lore: "三回幻形的白骨女妖",
        fullLore: "三回幻形的白骨女妖",
        grade: "SR",
        roleHint: "幻形",
        skills: [{ name: "化美", description: "扰乱对手心神" }, { name: "白骨", description: "穿透一次护体" }, { name: "逃影", description: "化骨躲开一击" }],
      },
      {
        id: "w_xiyou_heixiong",
        worldId: "w_xiyou",
        name: "黑熊精",
        nickname: "黑风大王",
        faction: "精怪",
        lore: "黑风山窃袈裟的熊妖",
        fullLore: "黑风山窃袈裟的熊妖",
        grade: "R",
        roleHint: "山寨",
        skills: [{ name: "黑风", description: "遮蔽视野迟滞" }, { name: "掌击", description: "近身砸开防线" }],
      },
      {
        id: "w_xiyou_huangfeng",
        worldId: "w_xiyou",
        name: "黄风怪",
        nickname: "黄风大王",
        faction: "精怪",
        lore: "黄风岭迷人眼的貂精",
        fullLore: "黄风岭迷人眼的貂精",
        grade: "R",
        roleHint: "风障",
        skills: [{ name: "黄风", description: "迷眼降低命中" }],
      },
      {
        id: "w_xiyou_jinjiao",
        worldId: "w_xiyou",
        name: "金角大王",
        nickname: "平顶山兄",
        faction: "精怪",
        lore: "太上老君看炉童子所化",
        fullLore: "太上老君看炉童子所化",
        grade: "SR",
        roleHint: "法宝",
        skills: [{ name: "紫金葫芦", description: "吸走一次攻势" }, { name: "幌金绳", description: "短暂缚住对手" }],
      },
      {
        id: "w_xiyou_yinjiao",
        worldId: "w_xiyou",
        name: "银角大王",
        nickname: "平顶山弟",
        faction: "精怪",
        lore: "与兄共用五件法宝的童子",
        fullLore: "与兄共用五件法宝的童子",
        grade: "SR",
        roleHint: "法宝",
        skills: [{ name: "羊脂玉净瓶", description: "收走残势" }, { name: "七星剑", description: "劈开一道护体" }],
      },
      {
        id: "w_xiyou_honghai",
        worldId: "w_xiyou",
        name: "红孩儿",
        nickname: "圣婴大王",
        faction: "精怪",
        lore: "牛魔王之子的三昧火童",
        fullLore: "牛魔王之子的三昧火童",
        grade: "SSR",
        roleHint: "三昧火",
        skills: [{ name: "火攻", description: "灼烧前方区域" }, { name: "车轮", description: "迅捷冲开人群" }, { name: "叫父", description: "引来短暂援势" }],
      },
      {
        id: "w_xiyou_tieshan",
        worldId: "w_xiyou",
        name: "铁扇公主",
        nickname: "罗刹女",
        faction: "精怪",
        lore: "芭蕉扇可熄火焰山",
        fullLore: "芭蕉扇可熄火焰山",
        grade: "SR",
        roleHint: "芭蕉扇",
        skills: [{ name: "扇风", description: "推开近身敌人" }, { name: "熄火", description: "化解一场灼烧" }],
      },
      {
        id: "w_xiyou_niumo",
        worldId: "w_xiyou",
        name: "牛魔王",
        nickname: "平天大圣",
        faction: "精怪",
        lore: "火焰山一带的霸主",
        fullLore: "火焰山一带的霸主",
        grade: "SSR",
        roleHint: "魔王",
        skills: [{ name: "化牛", description: "格挡一次冲击" }, { name: "踏山", description: "震地迟滞对手" }, { name: "联姻", description: "借势强化一回合" }],
      },
      {
        id: "w_xiyou_yumian",
        worldId: "w_xiyou",
        name: "玉面狐狸",
        nickname: "积雷山妾",
        faction: "精怪",
        lore: "依附牛魔的狐女",
        fullLore: "依附牛魔的狐女",
        grade: "R",
        roleHint: "狐媚",
        skills: [{ name: "媚术", description: "扰乱对手心神" }],
      },
      {
        id: "w_xiyou_liuer",
        worldId: "w_xiyou",
        name: "六耳猕猴",
        nickname: "假悟空",
        faction: "精怪",
        lore: "能乱真的分身精怪",
        fullLore: "能乱真的分身精怪",
        grade: "SSR",
        roleHint: "分身",
        skills: [{ name: "仿形", description: "错位躲开一击" }, { name: "乱真", description: "扰乱敌方判断" }, { name: "抢经", description: "夺取一场资源" }],
      },
      {
        id: "w_xiyou_xiezi",
        worldId: "w_xiyou",
        name: "蝎子精",
        nickname: "琵琶洞主",
        faction: "精怪",
        lore: "西梁女国的毒尾精",
        fullLore: "西梁女国的毒尾精",
        grade: "SR",
        roleHint: "毒尾",
        skills: [{ name: "蛰刺", description: "短暂迟滞对手" }, { name: "琴音", description: "扰乱心神" }],
      },
      {
        id: "w_xiyou_zhizhu",
        worldId: "w_xiyou",
        name: "蜘蛛精",
        nickname: "盘丝洞主",
        faction: "精怪",
        lore: "以丝网困人的女妖",
        fullLore: "以丝网困人的女妖",
        grade: "SR",
        roleHint: "丝网",
        skills: [{ name: "吐丝", description: "缚住对手脚步" }, { name: "七丝", description: "协同强化攻势" }],
      },
      {
        id: "w_xiyou_baiyan",
        worldId: "w_xiyou",
        name: "百眼魔君",
        nickname: "蜈蚣精",
        faction: "精怪",
        lore: "黄花观多目妖道",
        fullLore: "黄花观多目妖道",
        grade: "SR",
        roleHint: "多目",
        skills: [{ name: "金光", description: "远程压制一线" }, { name: "毒雾", description: "降低敌方节奏" }],
      },
      {
        id: "w_xiyou_qingshi",
        worldId: "w_xiyou",
        name: "青狮精",
        nickname: "狮驼王",
        faction: "精怪",
        lore: "狮驼岭吞人的狮精",
        fullLore: "狮驼岭吞人的狮精",
        grade: "SR",
        roleHint: "吞山",
        skills: [{ name: "巨口", description: "打断对手咏唱" }, { name: "狮吼", description: "震慑动摇人心" }],
      },
      {
        id: "w_xiyou_baixiang",
        worldId: "w_xiyou",
        name: "白象精",
        nickname: "二大王",
        faction: "精怪",
        lore: "狮驼岭卷人的象精",
        fullLore: "狮驼岭卷人的象精",
        grade: "R",
        roleHint: "卷鼻",
        skills: [{ name: "卷鼻", description: "拉近并迟滞敌人" }],
      },
      {
        id: "w_xiyou_dapeng",
        worldId: "w_xiyou",
        name: "大鹏雕",
        nickname: "三大王",
        faction: "精怪",
        lore: "狮驼岭展翅的雕精",
        fullLore: "狮驼岭展翅的雕精",
        grade: "SSR",
        roleHint: "展翅",
        skills: [{ name: "垂云", description: "俯冲砸开防线" }, { name: "金翅", description: "拉开交锋距离" }],
      },
      {
        id: "w_xiyou_huangmei",
        worldId: "w_xiyou",
        name: "黄眉大王",
        nickname: "小雷音妖",
        faction: "精怪",
        lore: "弥勒袋中逃出的黄眉童",
        fullLore: "弥勒袋中逃出的黄眉童",
        grade: "SR",
        roleHint: "假佛",
        skills: [{ name: "人种袋", description: "收走一场攻势" }, { name: "假佛", description: "虚势扰乱判断" }],
      },
      {
        id: "w_xiyou_diyong",
        worldId: "w_xiyou",
        name: "地涌夫人",
        nickname: "老鼠精",
        faction: "精怪",
        lore: "无底洞劫僧的鼠精",
        fullLore: "无底洞劫僧的鼠精",
        grade: "SR",
        roleHint: "地涌",
        skills: [{ name: "钻地", description: "错位躲开一击" }, { name: "绑僧", description: "短暂困住对手" }],
      },
      {
        id: "w_xiyou_yutu",
        worldId: "w_xiyou",
        name: "玉兔精",
        nickname: "月宫逃兔",
        faction: "精怪",
        lore: "天竺假公主的月兔",
        fullLore: "天竺假公主的月兔",
        grade: "SR",
        roleHint: "假亲",
        skills: [{ name: "捣药", description: "调息稳住己方" }, { name: "假姻", description: "扰乱对手心神" }],
      },
      {
        id: "w_xiyou_jiutou",
        worldId: "w_xiyou",
        name: "九头虫",
        nickname: "九头驸马",
        faction: "精怪",
        lore: "碧波潭的九头精怪",
        fullLore: "碧波潭的九头精怪",
        grade: "SR",
        roleHint: "九头",
        skills: [{ name: "分头", description: "同时袭扰两线" }, { name: "入水", description: "拉开距离逃开" }],
      },
      {
        id: "w_xiyou_huli",
        worldId: "w_xiyou",
        name: "虎力大仙",
        nickname: "车迟国师",
        faction: "精怪",
        lore: "与僧斗法的虎精",
        fullLore: "与僧斗法的虎精",
        grade: "R",
        roleHint: "假道",
        skills: [{ name: "祈雨", description: "改变战场节奏" }],
      },
      {
        id: "w_xiyou_luli",
        worldId: "w_xiyou",
        name: "鹿力大仙",
        nickname: "车迟国师",
        faction: "精怪",
        lore: "剖腹赌法的鹿精",
        fullLore: "剖腹赌法的鹿精",
        grade: "R",
        roleHint: "假道",
        skills: [{ name: "隔板", description: "虚势扰乱判断" }],
      },
      {
        id: "w_xiyou_yangli",
        worldId: "w_xiyou",
        name: "羊力大仙",
        nickname: "车迟国师",
        faction: "精怪",
        lore: "油锅赌法的羊精",
        fullLore: "油锅赌法的羊精",
        grade: "R",
        roleHint: "假道",
        skills: [{ name: "油锅", description: "反噬过猛攻势" }],
      },
      {
        id: "w_xiyou_dujiao",
        worldId: "w_xiyou",
        name: "独角兕",
        nickname: "青牛精",
        faction: "精怪",
        lore: "金兜洞的老君坐骑",
        fullLore: "金兜洞的老君坐骑",
        grade: "SR",
        roleHint: "金刚琢",
        skills: [{ name: "套索", description: "收走一次兵器势" }],
      },
      {
        id: "w_xiyou_huangpao",
        worldId: "w_xiyou",
        name: "黄袍怪",
        nickname: "奎木狼",
        faction: "精怪",
        lore: "宝象国摄公主的星宿",
        fullLore: "宝象国摄公主的星宿",
        grade: "SR",
        roleHint: "星宿",
        skills: [{ name: "化虎", description: "近身撕开防线" }, { name: "摄人", description: "短暂困住对手" }],
      },
      {
        id: "w_xiyou_xingxian",
        worldId: "w_xiyou",
        name: "杏仙",
        nickname: "木仙庵主",
        faction: "精怪",
        lore: "荆棘岭吟诗的树精",
        fullLore: "荆棘岭吟诗的树精",
        grade: "N",
        roleHint: "木魅",
        skills: [{ name: "落花", description: "扰乱对手心神" }],
      }
    ],
  },
  {
    id: "w_sanguo",
    title: "三国演义",
    genre: "CLASSICS",
    sourceHint: "罗贯中",
    lore: "汉末群雄逐鹿，魏蜀吴三分天下",
    fullLore: "黄巾乱后，董卓入京、诸侯讨伐，曹操挟天子令诸侯，刘备以仁义聚将，孙权坐断江东。赤壁之后三国鼎立，战场是中原、荆襄、巴蜀与江淮。计谋、阵法、水战火攻与坐骑兵刃并存，禁仙术飞升与现代枪械。",
    canonHint: "冷兵器、阵法、坐骑、权谋；禁枪械与仙术飞升",
    coverKey: "sanguo",
    official: true,
    presets: [
      {
        id: "w_sanguo_liubei",
        worldId: "w_sanguo",
        name: "刘备",
        nickname: "刘玄德",
        faction: "蜀汉",
        lore: "以仁义聚将的汉室宗亲",
        fullLore: "织席贩履起兵，桃园结义后辗转依附，赤壁后取荆入蜀称帝。卡面写仁义聚人与忍让，不写天命必胜。",
        grade: "SSR",
        roleHint: "主公",
        skills: [{ name: "仁义", description: "号召同伴并肩" }, { name: "三顾", description: "点破一门路径" }, { name: "摔阿斗", description: "稳住己方军心" }],
      },
      {
        id: "w_sanguo_zhuge",
        worldId: "w_sanguo",
        name: "诸葛亮",
        nickname: "卧龙",
        faction: "蜀汉",
        lore: "鞠躬尽瘁的军师",
        fullLore: "隆中对定三分，赤壁借东风之势，入蜀治国，六出祁山。技能写阵法计谋，不写预知必胜。",
        grade: "SSR",
        roleHint: "军师",
        skills: [{ name: "空城", description: "虚势扰乱判断" }, { name: "火计", description: "借势灼烧前方" }, { name: "八阵", description: "迟滞对手行动" }],
      },
      {
        id: "w_sanguo_guanyu",
        worldId: "w_sanguo",
        name: "关羽",
        nickname: "关云长",
        faction: "蜀汉",
        lore: "义薄云天的青龙骑将",
        fullLore: "义薄云天的青龙骑将",
        grade: "SSR",
        roleHint: "五虎",
        skills: [{ name: "青龙", description: "一骑当先破阵" }, { name: "义释", description: "暂缓敌方杀意" }, { name: "水淹", description: "改变战场节奏" }],
      },
      {
        id: "w_sanguo_zhangfei",
        worldId: "w_sanguo",
        name: "张飞",
        nickname: "张翼德",
        faction: "蜀汉",
        lore: "当阳喝断桥梁的猛将",
        fullLore: "当阳喝断桥梁的猛将",
        grade: "SSR",
        roleHint: "五虎",
        skills: [{ name: "断喝", description: "震慑动摇人心" }, { name: "矛刺", description: "近身撕开防线" }, { name: "醉矛", description: "以莽撞诱敌" }],
      },
      {
        id: "w_sanguo_zhaoyun",
        worldId: "w_sanguo",
        name: "赵云",
        nickname: "常山子龙",
        faction: "蜀汉",
        lore: "长坂坡救主的白马将",
        fullLore: "长坂坡救主的白马将",
        grade: "SSR",
        roleHint: "五虎",
        skills: [{ name: "回马", description: "拉开距离反击" }, { name: "一身是胆", description: "格挡一次冲击" }, { name: "龙枪", description: "突袭打断施法" }],
      },
      {
        id: "w_sanguo_machao",
        worldId: "w_sanguo",
        name: "马超",
        nickname: "锦马超",
        faction: "蜀汉",
        lore: "西凉铁骑的猛将",
        fullLore: "西凉铁骑的猛将",
        grade: "SR",
        roleHint: "五虎",
        skills: [{ name: "铁骑", description: "冲开人群破阵" }, { name: "枪影", description: "迅捷连刺前方" }],
      },
      {
        id: "w_sanguo_huangzhong",
        worldId: "w_sanguo",
        name: "黄忠",
        nickname: "老将黄忠",
        faction: "蜀汉",
        lore: "定军山夺隘的老将",
        fullLore: "定军山夺隘的老将",
        grade: "SR",
        roleHint: "五虎",
        skills: [{ name: "百步", description: "远程压制一线" }, { name: "夺隘", description: "击破后强化己方" }],
      },
      {
        id: "w_sanguo_weiyan",
        worldId: "w_sanguo",
        name: "魏延",
        nickname: "魏文长",
        faction: "蜀汉",
        lore: "傲而能战的汉中将",
        fullLore: "傲而能战的汉中将",
        grade: "SR",
        roleHint: "先锋",
        skills: [{ name: "子午", description: "险径突袭侧翼" }, { name: "反骨", description: "失手也能反制" }],
      },
      {
        id: "w_sanguo_jiangwei",
        worldId: "w_sanguo",
        name: "姜维",
        nickname: "姜伯约",
        faction: "蜀汉",
        lore: "继承北伐的凉州将",
        fullLore: "继承北伐的凉州将",
        grade: "SR",
        roleHint: "继业",
        skills: [{ name: "九伐", description: "连续施压节奏" }, { name: "屯田", description: "调息稳住己方" }],
      },
      {
        id: "w_sanguo_pangtong",
        worldId: "w_sanguo",
        name: "庞统",
        nickname: "凤雏",
        faction: "蜀汉",
        lore: "落凤坡前的奇谋士",
        fullLore: "落凤坡前的奇谋士",
        grade: "SR",
        roleHint: "军师",
        skills: [{ name: "连环", description: "迟滞对手行动" }, { name: "献策", description: "点破战场关键" }],
      },
      {
        id: "w_sanguo_fazheng",
        worldId: "w_sanguo",
        name: "法正",
        nickname: "法孝直",
        faction: "蜀汉",
        lore: "入蜀定计的冷面谋士",
        fullLore: "入蜀定计的冷面谋士",
        grade: "SR",
        roleHint: "谋主",
        skills: [{ name: "怨计", description: "针对破绽加压" }, { name: "取蜀", description: "借势强化攻势" }],
      },
      {
        id: "w_sanguo_xushu",
        worldId: "w_sanguo",
        name: "徐庶",
        nickname: "徐元直",
        faction: "蜀汉",
        lore: "走马荐诸葛的孝义谋士",
        fullLore: "走马荐诸葛的孝义谋士",
        grade: "R",
        roleHint: "谋士",
        skills: [{ name: "荐贤", description: "强化友方节奏" }, { name: "走马", description: "拉开交锋距离" }],
      },
      {
        id: "w_sanguo_masu",
        worldId: "w_sanguo",
        name: "马谡",
        nickname: "马幼常",
        faction: "蜀汉",
        lore: "街亭失守的理论派",
        fullLore: "街亭失守的理论派",
        grade: "N",
        roleHint: "参谋",
        skills: [{ name: "街亭", description: "虚势扰乱判断" }],
      },
      {
        id: "w_sanguo_guanping",
        worldId: "w_sanguo",
        name: "关平",
        nickname: "关将军嗣",
        faction: "蜀汉",
        lore: "随父镇荆的义子",
        fullLore: "随父镇荆的义子",
        grade: "R",
        roleHint: "偏将",
        skills: [{ name: "护刀", description: "贴身格挡杀机" }],
      },
      {
        id: "w_sanguo_zhoucang",
        worldId: "w_sanguo",
        name: "周仓",
        nickname: "周将军",
        faction: "蜀汉",
        lore: "扛刀随行的黄巾降将",
        fullLore: "扛刀随行的黄巾降将",
        grade: "R",
        roleHint: "亲随",
        skills: [{ name: "扛刀", description: "协同强化攻势" }],
      },
      {
        id: "w_sanguo_huangyueying",
        worldId: "w_sanguo",
        name: "黄月英",
        nickname: "黄氏",
        faction: "蜀汉",
        lore: "奇巧机关的隐士之女",
        fullLore: "奇巧机关的隐士之女",
        grade: "SR",
        roleHint: "巧思",
        skills: [{ name: "木牛", description: "加速己方节奏" }, { name: "流马", description: "补给稳住阵脚" }],
      },
      {
        id: "w_sanguo_liushan",
        worldId: "w_sanguo",
        name: "刘禅",
        nickname: "阿斗",
        faction: "蜀汉",
        lore: "守成却失锐的后主",
        fullLore: "守成却失锐的后主",
        grade: "N",
        roleHint: "后主",
        skills: [{ name: "乐不思蜀", description: "扰乱己方心神" }],
      },
      {
        id: "w_sanguo_liaohua",
        worldId: "w_sanguo",
        name: "廖化",
        nickname: "廖元俭",
        faction: "蜀汉",
        lore: "晚景仍出征的老将",
        fullLore: "晚景仍出征的老将",
        grade: "R",
        roleHint: "老将",
        skills: [{ name: "挡关", description: "格挡一次冲击" }],
      },
      {
        id: "w_sanguo_wangping",
        worldId: "w_sanguo",
        name: "王平",
        nickname: "句健",
        faction: "蜀汉",
        lore: "识地利的镇北将",
        fullLore: "识地利的镇北将",
        grade: "R",
        roleHint: "地利",
        skills: [{ name: "据水", description: "借地形迟滞敌人" }],
      },
      {
        id: "w_sanguo_caocao",
        worldId: "w_sanguo",
        name: "曹操",
        nickname: "曹孟德",
        faction: "曹魏",
        lore: "挟天子以令诸侯的枭雄",
        fullLore: "陈留起兵，官渡破袁，赤壁受挫后经营北方。多面：能容才也能忌才。技能写权谋军令，不写必胜。",
        grade: "SSR",
        roleHint: "主公",
        skills: [{ name: "奸雄", description: "以势压人夺先" }, { name: "令旗", description: "整军短暂强化" }, { name: "望梅", description: "虚势扰乱判断" }],
      },
      {
        id: "w_sanguo_simayi",
        worldId: "w_sanguo",
        name: "司马懿",
        nickname: "司马仲达",
        faction: "曹魏",
        lore: "隐忍待时的河内谋将",
        fullLore: "隐忍待时的河内谋将",
        grade: "SSR",
        roleHint: "权臣",
        skills: [{ name: "忍", description: "避锋蓄力再战" }, { name: "空城克", description: "识破虚势反击" }, { name: "拖", description: "迟滞对手行动" }],
      },
      {
        id: "w_sanguo_guojia",
        worldId: "w_sanguo",
        name: "郭嘉",
        nickname: "郭奉孝",
        faction: "曹魏",
        lore: "算无遗策却早逝的谋士",
        fullLore: "算无遗策却早逝的谋士",
        grade: "SSR",
        roleHint: "谋主",
        skills: [{ name: "十胜", description: "点破战场关键" }, { name: "遗计", description: "失手也能反制" }],
      },
      {
        id: "w_sanguo_xunyu",
        worldId: "w_sanguo",
        name: "荀彧",
        nickname: "荀文若",
        faction: "曹魏",
        lore: "王佐却与霸道相争的谋主",
        fullLore: "王佐却与霸道相争的谋主",
        grade: "SR",
        roleHint: "王佐",
        skills: [{ name: "守官渡", description: "稳住己方阵脚" }, { name: "让还", description: "暂缓一场冲突" }],
      },
      {
        id: "w_sanguo_jiaxu",
        worldId: "w_sanguo",
        name: "贾诩",
        nickname: "贾文和",
        faction: "曹魏",
        lore: "三姓家奴外号下的冷谋",
        fullLore: "三姓家奴外号下的冷谋",
        grade: "SR",
        roleHint: "毒士",
        skills: [{ name: "乱军", description: "扰乱对手判断" }, { name: "自保", description: "格挡一次冲击" }],
      },
      {
        id: "w_sanguo_chengyu",
        worldId: "w_sanguo",
        name: "程昱",
        nickname: "程仲德",
        faction: "曹魏",
        lore: "腹有良谋的险谋士",
        fullLore: "腹有良谋的险谋士",
        grade: "SR",
        roleHint: "险谋",
        skills: [{ name: "十日之粮", description: "搜刮战场残势" }],
      },
      {
        id: "w_sanguo_xiahou",
        worldId: "w_sanguo",
        name: "夏侯惇",
        nickname: "夏侯元让",
        faction: "曹魏",
        lore: "拔矢啖睛的宗亲猛将",
        fullLore: "拔矢啖睛的宗亲猛将",
        grade: "SR",
        roleHint: "宗将",
        skills: [{ name: "啖睛", description: "震慑动摇人心" }, { name: "盾冲", description: "近身砸开防线" }],
      },
      {
        id: "w_sanguo_xiahuyuan",
        worldId: "w_sanguo",
        name: "夏侯渊",
        nickname: "夏侯妙才",
        faction: "曹魏",
        lore: "疾行夺寨的西线将",
        fullLore: "疾行夺寨的西线将",
        grade: "SR",
        roleHint: "疾行",
        skills: [{ name: "千里", description: "迅捷绕到侧翼" }],
      },
      {
        id: "w_sanguo_zhangliao",
        worldId: "w_sanguo",
        name: "张辽",
        nickname: "张文远",
        faction: "曹魏",
        lore: "逍遥津八百破十万",
        fullLore: "逍遥津八百破十万",
        grade: "SSR",
        roleHint: "名将",
        skills: [{ name: "逍遥津", description: "突袭打断施法" }, { name: "喝退", description: "震慑动摇人心" }],
      },
      {
        id: "w_sanguo_xuhuang",
        worldId: "w_sanguo",
        name: "徐晃",
        nickname: "徐公明",
        faction: "曹魏",
        lore: "正正之旗的稳健将",
        fullLore: "正正之旗的稳健将",
        grade: "SR",
        roleHint: "名将",
        skills: [{ name: "正兵", description: "稳步压制一线" }],
      },
      {
        id: "w_sanguo_zhanghe",
        worldId: "w_sanguo",
        name: "张郃",
        nickname: "张儁乂",
        faction: "曹魏",
        lore: "巧变的河东将",
        fullLore: "巧变的河东将",
        grade: "SR",
        roleHint: "名将",
        skills: [{ name: "巧变", description: "错位躲开一击" }],
      },
      {
        id: "w_sanguo_yujin",
        worldId: "w_sanguo",
        name: "于禁",
        nickname: "于文则",
        faction: "曹魏",
        lore: "持重却失节于水淹",
        fullLore: "持重却失节于水淹",
        grade: "R",
        roleHint: "名将",
        skills: [{ name: "持重", description: "格挡一次冲击" }],
      },
      {
        id: "w_sanguo_yuejin",
        worldId: "w_sanguo",
        name: "乐进",
        nickname: "乐文谦",
        faction: "曹魏",
        lore: "先登的短小精悍将",
        fullLore: "先登的短小精悍将",
        grade: "R",
        roleHint: "先锋",
        skills: [{ name: "先登", description: "一骑当先破阵" }],
      },
      {
        id: "w_sanguo_dianwei",
        worldId: "w_sanguo",
        name: "典韦",
        nickname: "古之恶来",
        faction: "曹魏",
        lore: "死守营门的贴身护卫",
        fullLore: "死守营门的贴身护卫",
        grade: "SR",
        roleHint: "护卫",
        skills: [{ name: "双戟", description: "近身撕开防线" }, { name: "门卫", description: "贴身格挡杀机" }],
      },
      {
        id: "w_sanguo_xuchu",
        worldId: "w_sanguo",
        name: "许褚",
        nickname: "虎痴",
        faction: "曹魏",
        lore: "裸衣斗马超的力士",
        fullLore: "裸衣斗马超的力士",
        grade: "SR",
        roleHint: "力士",
        skills: [{ name: "裸衣", description: "以势压人夺先" }, { name: "力撼", description: "砸开一道护体" }],
      },
      {
        id: "w_sanguo_dengai",
        worldId: "w_sanguo",
        name: "邓艾",
        nickname: "邓士载",
        faction: "曹魏",
        lore: "偷渡阴平的奇袭将",
        fullLore: "偷渡阴平的奇袭将",
        grade: "SR",
        roleHint: "奇袭",
        skills: [{ name: "阴平", description: "险径突袭侧翼" }],
      },
      {
        id: "w_sanguo_zhonghui",
        worldId: "w_sanguo",
        name: "钟会",
        nickname: "钟士季",
        faction: "曹魏",
        lore: "灭蜀却自矜的谋将",
        fullLore: "灭蜀却自矜的谋将",
        grade: "R",
        roleHint: "谋将",
        skills: [{ name: "分兵", description: "同时袭扰两线" }],
      },
      {
        id: "w_sanguo_caoren",
        worldId: "w_sanguo",
        name: "曹仁",
        nickname: "曹子孝",
        faction: "曹魏",
        lore: "守樊城的宗室将",
        fullLore: "守樊城的宗室将",
        grade: "R",
        roleHint: "守将",
        skills: [{ name: "坚城", description: "格挡一次冲击" }],
      },
      {
        id: "w_sanguo_caopi",
        worldId: "w_sanguo",
        name: "曹丕",
        nickname: "魏文帝",
        faction: "曹魏",
        lore: "代汉称帝的继承者",
        fullLore: "代汉称帝的继承者",
        grade: "SR",
        roleHint: "继承",
        skills: [{ name: "禅代", description: "以势压人夺先" }, { name: "七步", description: "点破对方破绽" }],
      },
      {
        id: "w_sanguo_sunquan",
        worldId: "w_sanguo",
        name: "孙权",
        nickname: "孙仲谋",
        faction: "东吴",
        lore: "坐断东南的少年主",
        fullLore: "坐断东南的少年主",
        grade: "SSR",
        roleHint: "主公",
        skills: [{ name: "江东", description: "借水势稳住阵脚" }, { name: "用人", description: "强化友方节奏" }, { name: "守土", description: "格挡一次冲击" }],
      },
      {
        id: "w_sanguo_sunce",
        worldId: "w_sanguo",
        name: "孙策",
        nickname: "小霸王",
        faction: "东吴",
        lore: "开基江东的猛锐之主",
        fullLore: "开基江东的猛锐之主",
        grade: "SSR",
        roleHint: "开基",
        skills: [{ name: "霸王", description: "冲开人群破阵" }, { name: "轻骑", description: "迅捷绕到侧翼" }],
      },
      {
        id: "w_sanguo_sunjian",
        worldId: "w_sanguo",
        name: "孙坚",
        nickname: "江东猛虎",
        faction: "东吴",
        lore: "破洛阳得玉玺的先主",
        fullLore: "破洛阳得玉玺的先主",
        grade: "SR",
        roleHint: "先主",
        skills: [{ name: "猛虎", description: "近身撕开防线" }],
      },
      {
        id: "w_sanguo_zhouyu",
        worldId: "w_sanguo",
        name: "周瑜",
        nickname: "周公瑾",
        faction: "东吴",
        lore: "赤壁火攻的大都督",
        fullLore: "赤壁火攻的大都督",
        grade: "SSR",
        roleHint: "都督",
        skills: [{ name: "火攻", description: "借势灼烧前方" }, { name: "苦肉", description: "诱敌露出破绽" }, { name: "琴心", description: "扰乱对手心神" }],
      },
      {
        id: "w_sanguo_lusu",
        worldId: "w_sanguo",
        name: "鲁肃",
        nickname: "鲁子敬",
        faction: "东吴",
        lore: "联刘抗曹的长者",
        fullLore: "联刘抗曹的长者",
        grade: "SR",
        roleHint: "外交",
        skills: [{ name: "借荆", description: "暂缓一场冲突" }, { name: "联盟", description: "协同强化攻势" }],
      },
      {
        id: "w_sanguo_lvmeng",
        worldId: "w_sanguo",
        name: "吕蒙",
        nickname: "吕子明",
        faction: "东吴",
        lore: "白衣渡江的吴下阿蒙",
        fullLore: "白衣渡江的吴下阿蒙",
        grade: "SR",
        roleHint: "奇袭",
        skills: [{ name: "白衣", description: "隐蔽突袭侧翼" }, { name: "读书", description: "点破一门路径" }],
      },
      {
        id: "w_sanguo_luxun",
        worldId: "w_sanguo",
        name: "陆逊",
        nickname: "陆伯言",
        faction: "东吴",
        lore: "火烧连营的书生都督",
        fullLore: "火烧连营的书生都督",
        grade: "SSR",
        roleHint: "都督",
        skills: [{ name: "连营火", description: "借势灼烧前方" }, { name: "忍辱", description: "避锋蓄力再战" }],
      },
      {
        id: "w_sanguo_huanggai",
        worldId: "w_sanguo",
        name: "黄盖",
        nickname: "黄公覆",
        faction: "东吴",
        lore: "苦肉诈降的老将",
        fullLore: "苦肉诈降的老将",
        grade: "SR",
        roleHint: "苦肉",
        skills: [{ name: "诈降", description: "诱敌露出破绽" }, { name: "火船", description: "灼烧前方区域" }],
      },
      {
        id: "w_sanguo_ganning",
        worldId: "w_sanguo",
        name: "甘宁",
        nickname: "锦帆贼",
        faction: "东吴",
        lore: "百骑劫营的水军将",
        fullLore: "百骑劫营的水军将",
        grade: "SR",
        roleHint: "水军",
        skills: [{ name: "劫营", description: "突袭打断施法" }, { name: "锦帆", description: "水战拉开距离" }],
      },
      {
        id: "w_sanguo_taishici",
        worldId: "w_sanguo",
        name: "太史慈",
        nickname: "太史子义",
        faction: "东吴",
        lore: "神射义气的东莱将",
        fullLore: "神射义气的东莱将",
        grade: "SR",
        roleHint: "神射",
        skills: [{ name: "神箭", description: "远程压制一线" }, { name: "单骑", description: "一骑当先破阵" }],
      },
      {
        id: "w_sanguo_zhoutai",
        worldId: "w_sanguo",
        name: "周泰",
        nickname: "周幼平",
        faction: "东吴",
        lore: "护主遍体鳞伤的亲将",
        fullLore: "护主遍体鳞伤的亲将",
        grade: "R",
        roleHint: "护卫",
        skills: [{ name: "鳞伤", description: "贴身格挡杀机" }],
      },
      {
        id: "w_sanguo_daqiao",
        worldId: "w_sanguo",
        name: "大乔",
        nickname: "桥公长女",
        faction: "东吴",
        lore: "国色而系江东和战",
        fullLore: "国色而系江东和战",
        grade: "R",
        roleHint: "国色",
        skills: [{ name: "安江东", description: "稳住己方军心" }],
      },
      {
        id: "w_sanguo_xiaoqiao",
        worldId: "w_sanguo",
        name: "小乔",
        nickname: "桥公次女",
        faction: "东吴",
        lore: "公瑾之妻的江东佳人",
        fullLore: "公瑾之妻的江东佳人",
        grade: "R",
        roleHint: "国色",
        skills: [{ name: "铜雀", description: "扰乱对手心神" }],
      },
      {
        id: "w_sanguo_sunshangxiang",
        worldId: "w_sanguo",
        name: "孙尚香",
        nickname: "孙仁",
        faction: "东吴",
        lore: "弓马姻缘的郡主",
        fullLore: "弓马姻缘的郡主",
        grade: "SR",
        roleHint: "郡主",
        skills: [{ name: "弓马", description: "远程压制一线" }, { name: "归宁", description: "拉开交锋距离" }],
      },
      {
        id: "w_sanguo_zhangzhao",
        worldId: "w_sanguo",
        name: "张昭",
        nickname: "张子布",
        faction: "东吴",
        lore: "主降而直谏的顾命",
        fullLore: "主降而直谏的顾命",
        grade: "R",
        roleHint: "文臣",
        skills: [{ name: "直谏", description: "震慑动摇人心" }],
      },
      {
        id: "w_sanguo_lvbu",
        worldId: "w_sanguo",
        name: "吕布",
        nickname: "吕奉先",
        faction: "群雄",
        lore: "三姓而勇冠的骑将",
        fullLore: "丁原董卓之间反复，虎牢关与诸侯对峙后成公敌。勇冠三军，智谋不足。技能写骑战神射，不写无敌。",
        grade: "SSR",
        roleHint: "无双",
        skills: [{ name: "方天", description: "一骑当先破阵" }, { name: "赤兔", description: "迅捷绕到侧翼" }, { name: "辕门", description: "远程压制一线" }],
      },
      {
        id: "w_sanguo_diaochan",
        worldId: "w_sanguo",
        name: "貂蝉",
        nickname: "任红昌",
        faction: "群雄",
        lore: "连环计中的歌姬",
        fullLore: "连环计中的歌姬",
        grade: "SR",
        roleHint: "连环",
        skills: [{ name: "闭月", description: "扰乱对手心神" }, { name: "离间", description: "使敌方自乱节奏" }],
      },
      {
        id: "w_sanguo_dongzhuo",
        worldId: "w_sanguo",
        name: "董卓",
        nickname: "董仲颖",
        faction: "群雄",
        lore: "焚洛阳的西凉暴主",
        fullLore: "焚洛阳的西凉暴主",
        grade: "R",
        roleHint: "暴政",
        skills: [{ name: "迁都", description: "破坏敌方阵脚" }],
      },
      {
        id: "w_sanguo_yuanshao",
        worldId: "w_sanguo",
        name: "袁绍",
        nickname: "袁本初",
        faction: "群雄",
        lore: "四世三公却多谋少决",
        fullLore: "四世三公却多谋少决",
        grade: "SR",
        roleHint: "盟主",
        skills: [{ name: "盟主", description: "号召同伴并肩" }, { name: "官渡", description: "虚势扰乱判断" }],
      },
      {
        id: "w_sanguo_huaxiong",
        worldId: "w_sanguo",
        name: "华雄",
        nickname: "华将军",
        faction: "群雄",
        lore: "汜水关先声的西凉将",
        fullLore: "汜水关先声的西凉将",
        grade: "R",
        roleHint: "先锋",
        skills: [{ name: "温酒", description: "近身撕开防线" }],
      },
      {
        id: "w_sanguo_yanliang",
        worldId: "w_sanguo",
        name: "颜良",
        nickname: "河北名将",
        faction: "群雄",
        lore: "白马坡前的河北将",
        fullLore: "白马坡前的河北将",
        grade: "R",
        roleHint: "名将",
        skills: [{ name: "河北", description: "以势压人夺先" }],
      },
      {
        id: "w_sanguo_huatuo",
        worldId: "w_sanguo",
        name: "华佗",
        nickname: "华元化",
        faction: "群雄",
        lore: "刮骨疗伤的神医",
        fullLore: "刮骨疗伤的神医",
        grade: "SR",
        roleHint: "神医",
        skills: [{ name: "刮骨", description: "调息稳住己方" }, { name: "麻沸", description: "短暂迟滞对手" }],
      },
      {
        id: "w_sanguo_menghuo",
        worldId: "w_sanguo",
        name: "孟获",
        nickname: "南中王",
        faction: "群雄",
        lore: "七纵七擒的南中首领",
        fullLore: "七纵七擒的南中首领",
        grade: "SR",
        roleHint: "南中",
        skills: [{ name: "蛮兵", description: "协同强化攻势" }, { name: "再起", description: "失手也能反制" }],
      },
      {
        id: "w_sanguo_zuoci",
        worldId: "w_sanguo",
        name: "左慈",
        nickname: "乌角先生",
        faction: "群雄",
        lore: "戏曹操的方士",
        fullLore: "戏曹操的方士",
        grade: "SR",
        roleHint: "方术",
        skills: [{ name: "分杯", description: "错位躲开一击" }, { name: "羊群", description: "虚势扰乱判断" }],
      }
    ],
  },
  {
    id: "w_shuihu",
    title: "水浒传",
    genre: "CLASSICS",
    sourceHint: "施耐庵",
    lore: "水泊梁山聚义，替天行道较武",
    fullLore: "北宋末年，好汉因冤案、义气或被逼上梁山。晁盖劫生辰纲开局，宋江聚一百零八将排座次，有马军、步军、水军与头领。战场是梁山水泊、祝家庄、曾头市与征途关隘。拳脚兵刃、水战弓马皆可，禁法术飞升与火器。",
    canonHint: "兵刃、拳脚、水战、义气；禁飞升与枪炮",
    coverKey: "shuihu",
    official: true,
    presets: [
      {
        id: "w_shuihu_songjiang",
        worldId: "w_shuihu",
        name: "宋江",
        nickname: "及时雨",
        faction: "天罡",
        lore: "郓城义士聚义头领",
        fullLore: "郓城义士聚义头领",
        grade: "SSR",
        roleHint: "及时雨",
        skills: [{ name: "义聚", description: "号召同伴并肩" }, { name: "招安", description: "暂缓一场冲突" }, { name: "让先", description: "把锋芒让给队友" }],
      },
      {
        id: "w_shuihu_lujunyi",
        worldId: "w_shuihu",
        name: "卢俊义",
        nickname: "玉麒麟",
        faction: "天罡",
        lore: "大名府棍棒无对的员外",
        fullLore: "大名府棍棒无对的员外",
        grade: "SSR",
        roleHint: "玉麒麟",
        skills: [{ name: "棍势", description: "近身砸开防线" }, { name: "活捉", description: "短暂困住对手" }],
      },
      {
        id: "w_shuihu_wuyong",
        worldId: "w_shuihu",
        name: "吴用",
        nickname: "智多星",
        faction: "天罡",
        lore: "加亮先生的梁山军师",
        fullLore: "加亮先生的梁山军师",
        grade: "SSR",
        roleHint: "智多星",
        skills: [{ name: "生辰纲", description: "诱敌露出破绽" }, { name: "连环", description: "迟滞对手行动" }, { name: "借铃", description: "虚势扰乱判断" }],
      },
      {
        id: "w_shuihu_gongsun",
        worldId: "w_shuihu",
        name: "公孙胜",
        nickname: "入云龙",
        faction: "天罡",
        lore: "二仙山罗真人弟子",
        fullLore: "二仙山罗真人弟子",
        grade: "SR",
        roleHint: "入云龙",
        skills: [{ name: "呼风", description: "改变战场节奏" }, { name: "破法", description: "化解一次邪术" }],
      },
      {
        id: "w_shuihu_guansheng",
        worldId: "w_shuihu",
        name: "关胜",
        nickname: "大刀",
        faction: "天罡",
        lore: "青龙偃月的蒲东将",
        fullLore: "青龙偃月的蒲东将",
        grade: "SR",
        roleHint: "大刀",
        skills: [{ name: "大刀", description: "劈开一道防线" }, { name: "归义", description: "感化动摇人心" }],
      },
      {
        id: "w_shuihu_linchong",
        worldId: "w_shuihu",
        name: "林冲",
        nickname: "豹子头",
        faction: "天罡",
        lore: "八十万禁军枪棒教头",
        fullLore: "八十万禁军枪棒教头",
        grade: "SSR",
        roleHint: "豹子头",
        skills: [{ name: "回马", description: "拉开距离反击" }, { name: "雪夜", description: "突袭打断施法" }, { name: "火并", description: "击破后强化己方" }],
      },
      {
        id: "w_shuihu_qinming",
        worldId: "w_shuihu",
        name: "秦明",
        nickname: "霹雳火",
        faction: "天罡",
        lore: "狼牙棒当先的青州将",
        fullLore: "狼牙棒当先的青州将",
        grade: "SR",
        roleHint: "霹雳火",
        skills: [{ name: "霹雳", description: "震慑动摇人心" }, { name: "先锋", description: "一骑当先破阵" }],
      },
      {
        id: "w_shuihu_huyanzhuo",
        worldId: "w_shuihu",
        name: "呼延灼",
        nickname: "双鞭",
        faction: "天罡",
        lore: "连环马的汝宁统制",
        fullLore: "连环马的汝宁统制",
        grade: "SR",
        roleHint: "双鞭",
        skills: [{ name: "双鞭", description: "近身连打破阵" }, { name: "连环马", description: "冲开人群破阵" }],
      },
      {
        id: "w_shuihu_huarong",
        worldId: "w_shuihu",
        name: "花荣",
        nickname: "小李广",
        faction: "天罡",
        lore: "百步穿杨的清风寨将",
        fullLore: "百步穿杨的清风寨将",
        grade: "SSR",
        roleHint: "小李广",
        skills: [{ name: "神箭", description: "远程压制一线" }, { name: "银枪", description: "突袭打断施法" }],
      },
      {
        id: "w_shuihu_chaijin",
        worldId: "w_shuihu",
        name: "柴进",
        nickname: "小旋风",
        faction: "天罡",
        lore: "丹书铁券的沧州贵胄",
        fullLore: "丹书铁券的沧州贵胄",
        grade: "SR",
        roleHint: "小旋风",
        skills: [{ name: "疏财", description: "强化友方节奏" }, { name: "匿人", description: "隐蔽躲开一击" }],
      },
      {
        id: "w_shuihu_liying",
        worldId: "w_shuihu",
        name: "李应",
        nickname: "扑天雕",
        faction: "天罡",
        lore: "飞刀点钢枪的庄主",
        fullLore: "飞刀点钢枪的庄主",
        grade: "SR",
        roleHint: "扑天雕",
        skills: [{ name: "飞刀", description: "远程压制一线" }, { name: "点钢", description: "近身撕开防线" }],
      },
      {
        id: "w_shuihu_zhutong",
        worldId: "w_shuihu",
        name: "朱仝",
        nickname: "美髯公",
        faction: "天罡",
        lore: "有关公风采的都头",
        fullLore: "有关公风采的都头",
        grade: "R",
        roleHint: "美髯公",
        skills: [{ name: "美髯", description: "震慑动摇人心" }, { name: "私放", description: "暂缓一场冲突" }],
      },
      {
        id: "w_shuihu_luzhishen",
        worldId: "w_shuihu",
        name: "鲁智深",
        nickname: "花和尚",
        faction: "天罡",
        lore: "倒拔垂杨柳的提辖僧",
        fullLore: "倒拔垂杨柳的提辖僧",
        grade: "SSR",
        roleHint: "花和尚",
        skills: [{ name: "禅杖", description: "横扫近身敌人" }, { name: "三拳", description: "近身砸开防线" }, { name: "醉闹", description: "以莽撞诱敌" }],
      },
      {
        id: "w_shuihu_wusong",
        worldId: "w_shuihu",
        name: "武松",
        nickname: "行者",
        faction: "天罡",
        lore: "景阳冈走来的好汉",
        fullLore: "景阳冈走来的好汉",
        grade: "SSR",
        roleHint: "行者",
        skills: [{ name: "哨棒", description: "打断对手节奏" }, { name: "醉打", description: "借势近身连打" }, { name: "鸳鸯", description: "突袭撕开防线" }],
      },
      {
        id: "w_shuihu_dongping",
        worldId: "w_shuihu",
        name: "董平",
        nickname: "双枪将",
        faction: "天罡",
        lore: "凤流双枪的虎将",
        fullLore: "凤流双枪的虎将",
        grade: "SR",
        roleHint: "双枪将",
        skills: [{ name: "双枪", description: "同时袭扰两线" }],
      },
      {
        id: "w_shuihu_zhangqing",
        worldId: "w_shuihu",
        name: "张清",
        nickname: "没羽箭",
        faction: "天罡",
        lore: "飞石打将的奇射手",
        fullLore: "飞石打将的奇射手",
        grade: "SR",
        roleHint: "没羽箭",
        skills: [{ name: "飞石", description: "远程打断施法" }],
      },
      {
        id: "w_shuihu_yangzhi",
        worldId: "w_shuihu",
        name: "杨志",
        nickname: "青面兽",
        faction: "天罡",
        lore: "失陷花石纲的制使",
        fullLore: "失陷花石纲的制使",
        grade: "SR",
        roleHint: "青面兽",
        skills: [{ name: "朴刀", description: "近身撕开防线" }, { name: "押纲", description: "格挡一次冲击" }],
      },
      {
        id: "w_shuihu_xuning",
        worldId: "w_shuihu",
        name: "徐宁",
        nickname: "金枪手",
        faction: "天罡",
        lore: "钩镰枪破连环马",
        fullLore: "钩镰枪破连环马",
        grade: "SR",
        roleHint: "金枪手",
        skills: [{ name: "钩镰", description: "克制冲锋骑阵" }],
      },
      {
        id: "w_shuihu_suochao",
        worldId: "w_shuihu",
        name: "索超",
        nickname: "急先锋",
        faction: "天罡",
        lore: "性急先登的大名将",
        fullLore: "性急先登的大名将",
        grade: "R",
        roleHint: "急先锋",
        skills: [{ name: "急先锋", description: "一骑当先破阵" }],
      },
      {
        id: "w_shuihu_daizong",
        worldId: "w_shuihu",
        name: "戴宗",
        nickname: "神行太保",
        faction: "天罡",
        lore: "日行八百的信使",
        fullLore: "日行八百的信使",
        grade: "SR",
        roleHint: "神行太保",
        skills: [{ name: "神行", description: "迅捷绕到侧翼" }, { name: "传讯", description: "加速己方节奏" }],
      },
      {
        id: "w_shuihu_liutang",
        worldId: "w_shuihu",
        name: "刘唐",
        nickname: "赤发鬼",
        faction: "天罡",
        lore: "生辰纲案的急先锋",
        fullLore: "生辰纲案的急先锋",
        grade: "R",
        roleHint: "赤发鬼",
        skills: [{ name: "赤发", description: "近身撕开防线" }],
      },
      {
        id: "w_shuihu_likui",
        worldId: "w_shuihu",
        name: "李逵",
        nickname: "黑旋风",
        faction: "天罡",
        lore: "双斧莽撞的沂岭汉",
        fullLore: "双斧莽撞的沂岭汉",
        grade: "SSR",
        roleHint: "黑旋风",
        skills: [{ name: "双斧", description: "横扫近身敌人" }, { name: "莽撞", description: "以势压人夺先" }, { name: "护兄", description: "贴身格挡杀机" }],
      },
      {
        id: "w_shuihu_shijin",
        worldId: "w_shuihu",
        name: "史进",
        nickname: "九纹龙",
        faction: "天罡",
        lore: "史家庄习武的后生",
        fullLore: "史家庄习武的后生",
        grade: "SR",
        roleHint: "九纹龙",
        skills: [{ name: "九纹", description: "近身连打破阵" }],
      },
      {
        id: "w_shuihu_muhong",
        worldId: "w_shuihu",
        name: "穆弘",
        nickname: "没遮拦",
        faction: "天罡",
        lore: "揭阳镇的豪横庄主",
        fullLore: "揭阳镇的豪横庄主",
        grade: "R",
        roleHint: "没遮拦",
        skills: [{ name: "没遮拦", description: "冲开人群破阵" }],
      },
      {
        id: "w_shuihu_leiheng",
        worldId: "w_shuihu",
        name: "雷横",
        nickname: "插翅虎",
        faction: "天罡",
        lore: "步军都头的扑汉",
        fullLore: "步军都头的扑汉",
        grade: "R",
        roleHint: "插翅虎",
        skills: [{ name: "插翅", description: "迅捷绕到侧翼" }],
      },
      {
        id: "w_shuihu_lijun",
        worldId: "w_shuihu",
        name: "李俊",
        nickname: "混江龙",
        faction: "天罡",
        lore: "扬子江水军头领",
        fullLore: "扬子江水军头领",
        grade: "SR",
        roleHint: "混江龙",
        skills: [{ name: "混江", description: "水战拉开距离" }, { name: "船阵", description: "借水势稳住阵脚" }],
      },
      {
        id: "w_shuihu_ruanxiaoer",
        worldId: "w_shuihu",
        name: "阮小二",
        nickname: "立地太岁",
        faction: "天罡",
        lore: "石碣村渔人",
        fullLore: "石碣村渔人",
        grade: "R",
        roleHint: "立地太岁",
        skills: [{ name: "渔叉", description: "水战迟滞对手" }],
      },
      {
        id: "w_shuihu_zhangheng",
        worldId: "w_shuihu",
        name: "张横",
        nickname: "船火儿",
        faction: "天罡",
        lore: "浔阳江夜船好汉",
        fullLore: "浔阳江夜船好汉",
        grade: "R",
        roleHint: "船火儿",
        skills: [{ name: "夜船", description: "隐蔽突袭侧翼" }],
      },
      {
        id: "w_shuihu_ruanxiaowu",
        worldId: "w_shuihu",
        name: "阮小五",
        nickname: "短命二郎",
        faction: "天罡",
        lore: "石碣村短命二郎",
        fullLore: "石碣村短命二郎",
        grade: "R",
        roleHint: "短命二郎",
        skills: [{ name: "短兵", description: "近身撕开防线" }],
      },
      {
        id: "w_shuihu_zhangshun",
        worldId: "w_shuihu",
        name: "张顺",
        nickname: "浪里白条",
        faction: "天罡",
        lore: "能伏水的浪里白条",
        fullLore: "能伏水的浪里白条",
        grade: "SR",
        roleHint: "浪里白条",
        skills: [{ name: "潜水", description: "错位躲开一击" }, { name: "浪里", description: "水战拉开距离" }],
      },
      {
        id: "w_shuihu_ruanxiaoqi",
        worldId: "w_shuihu",
        name: "阮小七",
        nickname: "活阎罗",
        faction: "天罡",
        lore: "石碣村活阎罗",
        fullLore: "石碣村活阎罗",
        grade: "R",
        roleHint: "活阎罗",
        skills: [{ name: "活阎罗", description: "震慑动摇人心" }],
      },
      {
        id: "w_shuihu_yangxiong",
        worldId: "w_shuihu",
        name: "杨雄",
        nickname: "病关索",
        faction: "天罡",
        lore: "蓟州府病关索",
        fullLore: "蓟州府病关索",
        grade: "R",
        roleHint: "病关索",
        skills: [{ name: "朴刀", description: "近身撕开防线" }],
      },
      {
        id: "w_shuihu_shixiu",
        worldId: "w_shuihu",
        name: "石秀",
        nickname: "拼命三郎",
        faction: "天罡",
        lore: "敢探祝家庄的樵夫",
        fullLore: "敢探祝家庄的樵夫",
        grade: "SR",
        roleHint: "拼命三郎",
        skills: [{ name: "拼命", description: "失手也能反制" }, { name: "探庄", description: "探明潜藏杀机" }],
      },
      {
        id: "w_shuihu_xiezhen",
        worldId: "w_shuihu",
        name: "解珍",
        nickname: "两头蛇",
        faction: "天罡",
        lore: "登州猎户兄",
        fullLore: "登州猎户兄",
        grade: "R",
        roleHint: "两头蛇",
        skills: [{ name: "猎叉", description: "远程压制一线" }],
      },
      {
        id: "w_shuihu_xiebao",
        worldId: "w_shuihu",
        name: "解宝",
        nickname: "双尾蝎",
        faction: "天罡",
        lore: "登州猎户弟",
        fullLore: "登州猎户弟",
        grade: "R",
        roleHint: "双尾蝎",
        skills: [{ name: "猎索", description: "短暂困住对手" }],
      },
      {
        id: "w_shuihu_yanqing",
        worldId: "w_shuihu",
        name: "燕青",
        nickname: "浪子",
        faction: "天罡",
        lore: "吹弹相扑的卢员外随从",
        fullLore: "吹弹相扑的卢员外随从",
        grade: "SSR",
        roleHint: "浪子",
        skills: [{ name: "相扑", description: "近身摔开敌人" }, { name: "冷箭", description: "远程打断施法" }, { name: "脱身", description: "错位躲开一击" }],
      },
      {
        id: "w_shuihu_zhuwu",
        worldId: "w_shuihu",
        name: "朱武",
        nickname: "神机军师",
        faction: "地煞",
        lore: "少华山副军师",
        fullLore: "少华山副军师",
        grade: "R",
        roleHint: "神机军师",
        skills: [{ name: "神机", description: "点破战场关键" }],
      },
      {
        id: "w_shuihu_huangxin",
        worldId: "w_shuihu",
        name: "黄信",
        nickname: "镇三山",
        faction: "地煞",
        lore: "青州兵马都监",
        fullLore: "青州兵马都监",
        grade: "R",
        roleHint: "镇三山",
        skills: [{ name: "镇三山", description: "格挡一次冲击" }],
      },
      {
        id: "w_shuihu_sunli",
        worldId: "w_shuihu",
        name: "孙立",
        nickname: "病尉迟",
        faction: "地煞",
        lore: "登州病尉迟",
        fullLore: "登州病尉迟",
        grade: "SR",
        roleHint: "病尉迟",
        skills: [{ name: "鞭锏", description: "近身连打破阵" }],
      },
      {
        id: "w_shuihu_xuanzen",
        worldId: "w_shuihu",
        name: "宣赞",
        nickname: "丑郡马",
        faction: "地煞",
        lore: "丑郡马宣赞",
        fullLore: "丑郡马宣赞",
        grade: "R",
        roleHint: "丑郡马",
        skills: [{ name: "郡马", description: "以势压人夺先" }],
      },
      {
        id: "w_shuihu_haosiwen",
        worldId: "w_shuihu",
        name: "郝思文",
        nickname: "井木犴",
        faction: "地煞",
        lore: "关胜副将",
        fullLore: "关胜副将",
        grade: "R",
        roleHint: "井木犴",
        skills: [{ name: "副将", description: "协同强化攻势" }],
      },
      {
        id: "w_shuihu_hantao",
        worldId: "w_shuihu",
        name: "韩滔",
        nickname: "百胜将",
        faction: "地煞",
        lore: "连环马部将",
        fullLore: "连环马部将",
        grade: "R",
        roleHint: "百胜将",
        skills: [{ name: "百胜", description: "稳步压制一线" }],
      },
      {
        id: "w_shuihu_pengqi",
        worldId: "w_shuihu",
        name: "彭玘",
        nickname: "天目将",
        faction: "地煞",
        lore: "呼延灼部将",
        fullLore: "呼延灼部将",
        grade: "R",
        roleHint: "天目将",
        skills: [{ name: "天目", description: "看破潜藏杀机" }],
      },
      {
        id: "w_shuihu_shantinggui",
        worldId: "w_shuihu",
        name: "单廷珪",
        nickname: "圣水将",
        faction: "地煞",
        lore: "圣水将单廷珪",
        fullLore: "圣水将单廷珪",
        grade: "R",
        roleHint: "圣水将",
        skills: [{ name: "圣水", description: "化解一场灼烧" }],
      },
      {
        id: "w_shuihu_weidingguo",
        worldId: "w_shuihu",
        name: "魏定国",
        nickname: "神火将",
        faction: "地煞",
        lore: "神火将魏定国",
        fullLore: "神火将魏定国",
        grade: "R",
        roleHint: "神火将",
        skills: [{ name: "神火", description: "灼烧前方区域" }],
      },
      {
        id: "w_shuihu_xiaorang",
        worldId: "w_shuihu",
        name: "萧让",
        nickname: "圣手书生",
        faction: "地煞",
        lore: "能仿蔡京字的书生",
        fullLore: "能仿蔡京字的书生",
        grade: "R",
        roleHint: "圣手书生",
        skills: [{ name: "仿书", description: "虚势扰乱判断" }],
      },
      {
        id: "w_shuihu_peixuan",
        worldId: "w_shuihu",
        name: "裴宣",
        nickname: "铁面孔目",
        faction: "地煞",
        lore: "铁面无私的赏罚官",
        fullLore: "铁面无私的赏罚官",
        grade: "R",
        roleHint: "铁面孔目",
        skills: [{ name: "赏罚", description: "点破不公关键" }],
      },
      {
        id: "w_shuihu_oupeng",
        worldId: "w_shuihu",
        name: "欧鹏",
        nickname: "摩云金翅",
        faction: "地煞",
        lore: "黄门山头领",
        fullLore: "黄门山头领",
        grade: "R",
        roleHint: "摩云金翅",
        skills: [{ name: "金翅", description: "迅捷绕到侧翼" }],
      },
      {
        id: "w_shuihu_dengfei",
        worldId: "w_shuihu",
        name: "邓飞",
        nickname: "火眼狻猊",
        faction: "地煞",
        lore: "火眼狻猊邓飞",
        fullLore: "火眼狻猊邓飞",
        grade: "R",
        roleHint: "火眼狻猊",
        skills: [{ name: "火眼", description: "看破幻形伪装" }],
      },
      {
        id: "w_shuihu_yanshun",
        worldId: "w_shuihu",
        name: "燕顺",
        nickname: "锦毛虎",
        faction: "地煞",
        lore: "清风山锦毛虎",
        fullLore: "清风山锦毛虎",
        grade: "R",
        roleHint: "锦毛虎",
        skills: [{ name: "锦毛", description: "近身撕开防线" }],
      },
      {
        id: "w_shuihu_yanglin",
        worldId: "w_shuihu",
        name: "杨林",
        nickname: "锦豹子",
        faction: "地煞",
        lore: "锦豹子杨林",
        fullLore: "锦豹子杨林",
        grade: "R",
        roleHint: "锦豹子",
        skills: [{ name: "锦豹", description: "突袭打断施法" }],
      },
      {
        id: "w_shuihu_lingzhen",
        worldId: "w_shuihu",
        name: "凌振",
        nickname: "轰天雷",
        faction: "地煞",
        lore: "制造火炮的炮手",
        fullLore: "制造火炮的炮手",
        grade: "SR",
        roleHint: "轰天雷",
        skills: [{ name: "号炮", description: "震慑动摇人心" }, { name: "火炮", description: "远程压制一线" }],
      },
      {
        id: "w_shuihu_jiangjing",
        worldId: "w_shuihu",
        name: "蒋敬",
        nickname: "神算子",
        faction: "地煞",
        lore: "钱粮会计神算",
        fullLore: "钱粮会计神算",
        grade: "R",
        roleHint: "神算子",
        skills: [{ name: "神算", description: "点破一门路径" }],
      },
      {
        id: "w_shuihu_lvfang",
        worldId: "w_shuihu",
        name: "吕方",
        nickname: "小温侯",
        faction: "地煞",
        lore: "画杆方天戟",
        fullLore: "画杆方天戟",
        grade: "R",
        roleHint: "小温侯",
        skills: [{ name: "方天", description: "一骑当先破阵" }],
      },
      {
        id: "w_shuihu_guosheng",
        worldId: "w_shuihu",
        name: "郭盛",
        nickname: "赛仁贵",
        faction: "地煞",
        lore: "赛仁贵郭盛",
        fullLore: "赛仁贵郭盛",
        grade: "R",
        roleHint: "赛仁贵",
        skills: [{ name: "画戟", description: "近身撕开防线" }],
      },
      {
        id: "w_shuihu_andaoquan",
        worldId: "w_shuihu",
        name: "安道全",
        nickname: "神医",
        faction: "地煞",
        lore: "内外科神医",
        fullLore: "内外科神医",
        grade: "SR",
        roleHint: "神医",
        skills: [{ name: "神医", description: "调息稳住己方" }, { name: "金疮", description: "化解一次创伤" }],
      },
      {
        id: "w_shuihu_huangfuduan",
        worldId: "w_shuihu",
        name: "皇甫端",
        nickname: "紫髯伯",
        faction: "地煞",
        lore: "兽医紫髯伯",
        fullLore: "兽医紫髯伯",
        grade: "R",
        roleHint: "紫髯伯",
        skills: [{ name: "疗马", description: "强化骑战节奏" }],
      },
      {
        id: "w_shuihu_wangying",
        worldId: "w_shuihu",
        name: "王英",
        nickname: "矮脚虎",
        faction: "地煞",
        lore: "清风山矮脚虎",
        fullLore: "清风山矮脚虎",
        grade: "N",
        roleHint: "矮脚虎",
        skills: [{ name: "矮脚", description: "近身撕开防线" }],
      },
      {
        id: "w_shuihu_husanniang",
        worldId: "w_shuihu",
        name: "扈三娘",
        nickname: "一丈青",
        faction: "地煞",
        lore: "祝家庄女将",
        fullLore: "祝家庄女将",
        grade: "SR",
        roleHint: "一丈青",
        skills: [{ name: "双刀", description: "近身连打破阵" }, { name: "红锦", description: "迅捷绕到侧翼" }],
      },
      {
        id: "w_shuihu_baoxu",
        worldId: "w_shuihu",
        name: "鲍旭",
        nickname: "丧门神",
        faction: "地煞",
        lore: "枯树山丧门神",
        fullLore: "枯树山丧门神",
        grade: "R",
        roleHint: "丧门神",
        skills: [{ name: "丧门", description: "震慑动摇人心" }],
      },
      {
        id: "w_shuihu_fanrui",
        worldId: "w_shuihu",
        name: "樊瑞",
        nickname: "混世魔王",
        faction: "地煞",
        lore: "芒砀山道术头领",
        fullLore: "芒砀山道术头领",
        grade: "SR",
        roleHint: "混世魔王",
        skills: [{ name: "魔障", description: "迟滞对手行动" }],
      },
      {
        id: "w_shuihu_kongming",
        worldId: "w_shuihu",
        name: "孔明",
        nickname: "毛头星",
        faction: "地煞",
        lore: "白虎山毛头星",
        fullLore: "白虎山毛头星",
        grade: "R",
        roleHint: "毛头星",
        skills: [{ name: "毛头", description: "协同强化攻势" }],
      },
      {
        id: "w_shuihu_kongliang",
        worldId: "w_shuihu",
        name: "孔亮",
        nickname: "独火星",
        faction: "地煞",
        lore: "白虎山独火星",
        fullLore: "白虎山独火星",
        grade: "R",
        roleHint: "独火星",
        skills: [{ name: "独火", description: "灼烧前方区域" }],
      },
      {
        id: "w_shuihu_xiangchong",
        worldId: "w_shuihu",
        name: "项充",
        nickname: "八臂哪吒",
        faction: "地煞",
        lore: "飞刀牌手项充",
        fullLore: "飞刀牌手项充",
        grade: "R",
        roleHint: "八臂哪吒",
        skills: [{ name: "飞刀牌", description: "远程压制一线" }],
      },
      {
        id: "w_shuihu_ligun",
        worldId: "w_shuihu",
        name: "李衮",
        nickname: "飞天大圣",
        faction: "地煞",
        lore: "飞刀牌手李衮",
        fullLore: "飞刀牌手李衮",
        grade: "R",
        roleHint: "飞天大圣",
        skills: [{ name: "牌飞", description: "格挡一次冲击" }],
      },
      {
        id: "w_shuihu_jindajian",
        worldId: "w_shuihu",
        name: "金大坚",
        nickname: "玉臂匠",
        faction: "地煞",
        lore: "刻印符信的匠人",
        fullLore: "刻印符信的匠人",
        grade: "R",
        roleHint: "玉臂匠",
        skills: [{ name: "刻印", description: "虚势扰乱判断" }],
      },
      {
        id: "w_shuihu_malin",
        worldId: "w_shuihu",
        name: "马麟",
        nickname: "铁笛仙",
        faction: "地煞",
        lore: "铁笛仙马麟",
        fullLore: "铁笛仙马麟",
        grade: "R",
        roleHint: "铁笛仙",
        skills: [{ name: "铁笛", description: "扰乱对手心神" }],
      },
      {
        id: "w_shuihu_tongwei",
        worldId: "w_shuihu",
        name: "童威",
        nickname: "出洞蛟",
        faction: "地煞",
        lore: "李俊水军副手",
        fullLore: "李俊水军副手",
        grade: "R",
        roleHint: "出洞蛟",
        skills: [{ name: "出洞", description: "水战突袭侧翼" }],
      },
      {
        id: "w_shuihu_tongmeng",
        worldId: "w_shuihu",
        name: "童猛",
        nickname: "翻江蜃",
        faction: "地煞",
        lore: "李俊水军副手",
        fullLore: "李俊水军副手",
        grade: "R",
        roleHint: "翻江蜃",
        skills: [{ name: "翻江", description: "水战拉开距离" }],
      },
      {
        id: "w_shuihu_mengkang",
        worldId: "w_shuihu",
        name: "孟康",
        nickname: "玉幡竿",
        faction: "地煞",
        lore: "造船监督孟康",
        fullLore: "造船监督孟康",
        grade: "R",
        roleHint: "玉幡竿",
        skills: [{ name: "造船", description: "稳住水战阵脚" }],
      },
      {
        id: "w_shuihu_houjian",
        worldId: "w_shuihu",
        name: "侯健",
        nickname: "通臂猿",
        faction: "地煞",
        lore: "裁缝通臂猿",
        fullLore: "裁缝通臂猿",
        grade: "N",
        roleHint: "通臂猿",
        skills: [{ name: "通臂", description: "加速己方节奏" }],
      },
      {
        id: "w_shuihu_chenda",
        worldId: "w_shuihu",
        name: "陈达",
        nickname: "跳涧虎",
        faction: "地煞",
        lore: "少华山跳涧虎",
        fullLore: "少华山跳涧虎",
        grade: "R",
        roleHint: "跳涧虎",
        skills: [{ name: "跳涧", description: "迅捷绕到侧翼" }],
      },
      {
        id: "w_shuihu_yangchun",
        worldId: "w_shuihu",
        name: "杨春",
        nickname: "白花蛇",
        faction: "地煞",
        lore: "少华山白花蛇",
        fullLore: "少华山白花蛇",
        grade: "R",
        roleHint: "白花蛇",
        skills: [{ name: "白花", description: "近身撕开防线" }],
      },
      {
        id: "w_shuihu_zhengtian",
        worldId: "w_shuihu",
        name: "郑天寿",
        nickname: "白面郎君",
        faction: "地煞",
        lore: "白面郎君郑天寿",
        fullLore: "白面郎君郑天寿",
        grade: "N",
        roleHint: "白面郎君",
        skills: [{ name: "白面", description: "扰乱对手心神" }],
      },
      {
        id: "w_shuihu_taozongwang",
        worldId: "w_shuihu",
        name: "陶宗旺",
        nickname: "九尾龟",
        faction: "地煞",
        lore: "开掘城壕的庄客",
        fullLore: "开掘城壕的庄客",
        grade: "R",
        roleHint: "九尾龟",
        skills: [{ name: "掘壕", description: "迟滞对手行动" }],
      },
      {
        id: "w_shuihu_songqing",
        worldId: "w_shuihu",
        name: "宋清",
        nickname: "铁扇子",
        faction: "地煞",
        lore: "掌管筵席的宋清",
        fullLore: "掌管筵席的宋清",
        grade: "N",
        roleHint: "铁扇子",
        skills: [{ name: "筵席", description: "稳住己方军心" }],
      },
      {
        id: "w_shuihu_lehe",
        worldId: "w_shuihu",
        name: "乐和",
        nickname: "铁叫子",
        faction: "地煞",
        lore: "善唱能探的乐和",
        fullLore: "善唱能探的乐和",
        grade: "R",
        roleHint: "铁叫子",
        skills: [{ name: "传讯", description: "加速己方节奏" }],
      },
      {
        id: "w_shuihu_gongwang",
        worldId: "w_shuihu",
        name: "龚旺",
        nickname: "花项虎",
        faction: "地煞",
        lore: "花项虎龚旺",
        fullLore: "花项虎龚旺",
        grade: "R",
        roleHint: "花项虎",
        skills: [{ name: "花项", description: "近身撕开防线" }],
      },
      {
        id: "w_shuihu_dingdesun",
        worldId: "w_shuihu",
        name: "丁得孙",
        nickname: "中箭虎",
        faction: "地煞",
        lore: "中箭虎丁得孙",
        fullLore: "中箭虎丁得孙",
        grade: "R",
        roleHint: "中箭虎",
        skills: [{ name: "中箭", description: "远程压制一线" }],
      },
      {
        id: "w_shuihu_muchun",
        worldId: "w_shuihu",
        name: "穆春",
        nickname: "小遮拦",
        faction: "地煞",
        lore: "揭阳镇小遮拦",
        fullLore: "揭阳镇小遮拦",
        grade: "N",
        roleHint: "小遮拦",
        skills: [{ name: "小遮拦", description: "冲开人群破阵" }],
      },
      {
        id: "w_shuihu_caozheng",
        worldId: "w_shuihu",
        name: "曹正",
        nickname: "操刀鬼",
        faction: "地煞",
        lore: "屠户操刀鬼",
        fullLore: "屠户操刀鬼",
        grade: "R",
        roleHint: "操刀鬼",
        skills: [{ name: "操刀", description: "近身撕开防线" }],
      },
      {
        id: "w_shuihu_songwan",
        worldId: "w_shuihu",
        name: "宋万",
        nickname: "云里金刚",
        faction: "地煞",
        lore: "梁山早期头领",
        fullLore: "梁山早期头领",
        grade: "N",
        roleHint: "云里金刚",
        skills: [{ name: "云里", description: "格挡一次冲击" }],
      },
      {
        id: "w_shuihu_duqian",
        worldId: "w_shuihu",
        name: "杜迁",
        nickname: "摸着天",
        faction: "地煞",
        lore: "梁山早期头领",
        fullLore: "梁山早期头领",
        grade: "N",
        roleHint: "摸着天",
        skills: [{ name: "摸着天", description: "探明潜藏杀机" }],
      },
      {
        id: "w_shuihu_xueyong",
        worldId: "w_shuihu",
        name: "薛永",
        nickname: "病大虫",
        faction: "地煞",
        lore: "使枪卖药的病大虫",
        fullLore: "使枪卖药的病大虫",
        grade: "R",
        roleHint: "病大虫",
        skills: [{ name: "病虫", description: "近身撕开防线" }],
      },
      {
        id: "w_shuihu_shien",
        worldId: "w_shuihu",
        name: "施恩",
        nickname: "金眼彪",
        faction: "地煞",
        lore: "孟州牢城施恩",
        fullLore: "孟州牢城施恩",
        grade: "R",
        roleHint: "金眼彪",
        skills: [{ name: "金眼", description: "看破潜藏杀机" }],
      },
      {
        id: "w_shuihu_lizhong",
        worldId: "w_shuihu",
        name: "李忠",
        nickname: "打虎将",
        faction: "地煞",
        lore: "史家庄打虎将",
        fullLore: "史家庄打虎将",
        grade: "N",
        roleHint: "打虎将",
        skills: [{ name: "打虎", description: "近身砸开防线" }],
      },
      {
        id: "w_shuihu_zhoutong",
        worldId: "w_shuihu",
        name: "周通",
        nickname: "小霸王",
        faction: "地煞",
        lore: "桃花山小霸王",
        fullLore: "桃花山小霸王",
        grade: "N",
        roleHint: "小霸王",
        skills: [{ name: "小霸", description: "以势压人夺先" }],
      },
      {
        id: "w_shuihu_tanglong",
        worldId: "w_shuihu",
        name: "汤隆",
        nickname: "金钱豹子",
        faction: "地煞",
        lore: "打造甲胄的铁匠",
        fullLore: "打造甲胄的铁匠",
        grade: "R",
        roleHint: "金钱豹子",
        skills: [{ name: "打铁", description: "强化友方兵器" }],
      },
      {
        id: "w_shuihu_duxing",
        worldId: "w_shuihu",
        name: "杜兴",
        nickname: "鬼脸儿",
        faction: "地煞",
        lore: "李家庄主管",
        fullLore: "李家庄主管",
        grade: "R",
        roleHint: "鬼脸儿",
        skills: [{ name: "鬼脸", description: "扰乱对手判断" }],
      },
      {
        id: "w_shuihu_zouyuan",
        worldId: "w_shuihu",
        name: "邹渊",
        nickname: "出林龙",
        faction: "地煞",
        lore: "登云山出林龙",
        fullLore: "登云山出林龙",
        grade: "R",
        roleHint: "出林龙",
        skills: [{ name: "出林", description: "隐蔽突袭侧翼" }],
      },
      {
        id: "w_shuihu_zourun",
        worldId: "w_shuihu",
        name: "邹润",
        nickname: "独角龙",
        faction: "地煞",
        lore: "登云山独角龙",
        fullLore: "登云山独角龙",
        grade: "R",
        roleHint: "独角龙",
        skills: [{ name: "独角", description: "近身撕开防线" }],
      },
      {
        id: "w_shuihu_zhugui",
        worldId: "w_shuihu",
        name: "朱贵",
        nickname: "旱地忽律",
        faction: "地煞",
        lore: "梁山酒店探事",
        fullLore: "梁山酒店探事",
        grade: "SR",
        roleHint: "旱地忽律",
        skills: [{ name: "酒店", description: "探明潜藏杀机" }, { name: "接应", description: "隐蔽躲开一击" }],
      },
      {
        id: "w_shuihu_zhufu",
        worldId: "w_shuihu",
        name: "朱富",
        nickname: "笑面虎",
        faction: "地煞",
        lore: "酿酒的笑面虎",
        fullLore: "酿酒的笑面虎",
        grade: "N",
        roleHint: "笑面虎",
        skills: [{ name: "酿酒", description: "调息稳住己方" }],
      },
      {
        id: "w_shuihu_caifu",
        worldId: "w_shuihu",
        name: "蔡福",
        nickname: "铁臂膊",
        faction: "地煞",
        lore: "大名府刽子手",
        fullLore: "大名府刽子手",
        grade: "R",
        roleHint: "铁臂膊",
        skills: [{ name: "铁臂", description: "近身砸开防线" }],
      },
      {
        id: "w_shuihu_caiqing",
        worldId: "w_shuihu",
        name: "蔡庆",
        nickname: "一枝花",
        faction: "地煞",
        lore: "一枝花蔡庆",
        fullLore: "一枝花蔡庆",
        grade: "N",
        roleHint: "一枝花",
        skills: [{ name: "一枝花", description: "扰乱对手心神" }],
      },
      {
        id: "w_shuihu_lili",
        worldId: "w_shuihu",
        name: "李立",
        nickname: "催命判官",
        faction: "地煞",
        lore: "揭阳岭催命判官",
        fullLore: "揭阳岭催命判官",
        grade: "R",
        roleHint: "催命判官",
        skills: [{ name: "催命", description: "震慑动摇人心" }],
      },
      {
        id: "w_shuihu_liyun",
        worldId: "w_shuihu",
        name: "李云",
        nickname: "青眼虎",
        faction: "地煞",
        lore: "沂水县都头",
        fullLore: "沂水县都头",
        grade: "R",
        roleHint: "青眼虎",
        skills: [{ name: "青眼", description: "看破潜藏杀机" }],
      },
      {
        id: "w_shuihu_jiaoting",
        worldId: "w_shuihu",
        name: "焦挺",
        nickname: "没面目",
        faction: "地煞",
        lore: "没面目焦挺",
        fullLore: "没面目焦挺",
        grade: "N",
        roleHint: "没面目",
        skills: [{ name: "没面目", description: "近身撕开防线" }],
      },
      {
        id: "w_shuihu_shiyong",
        worldId: "w_shuihu",
        name: "石勇",
        nickname: "石将军",
        faction: "地煞",
        lore: "石将军石勇",
        fullLore: "石将军石勇",
        grade: "R",
        roleHint: "石将军",
        skills: [{ name: "石将", description: "格挡一次冲击" }],
      },
      {
        id: "w_shuihu_sunxin",
        worldId: "w_shuihu",
        name: "孙新",
        nickname: "小尉迟",
        faction: "地煞",
        lore: "登州小尉迟",
        fullLore: "登州小尉迟",
        grade: "R",
        roleHint: "小尉迟",
        skills: [{ name: "小尉迟", description: "近身连打破阵" }],
      },
      {
        id: "w_shuihu_gudashao",
        worldId: "w_shuihu",
        name: "顾大嫂",
        nickname: "母大虫",
        faction: "地煞",
        lore: "孙新之妻母大虫",
        fullLore: "孙新之妻母大虫",
        grade: "SR",
        roleHint: "母大虫",
        skills: [{ name: "母大虫", description: "近身撕开防线" }, { name: "劫狱", description: "突袭打断施法" }],
      },
      {
        id: "w_shuihu_zhangqing2",
        worldId: "w_shuihu",
        name: "张青",
        nickname: "菜园子",
        faction: "地煞",
        lore: "十字坡菜园子",
        fullLore: "十字坡菜园子",
        grade: "R",
        roleHint: "菜园子",
        skills: [{ name: "蒙汗", description: "短暂迟滞对手" }],
      },
      {
        id: "w_shuihu_sunerniang",
        worldId: "w_shuihu",
        name: "孙二娘",
        nickname: "母夜叉",
        faction: "地煞",
        lore: "十字坡母夜叉",
        fullLore: "十字坡母夜叉",
        grade: "SR",
        roleHint: "母夜叉",
        skills: [{ name: "母夜叉", description: "扰乱对手心神" }, { name: "开店", description: "诱敌露出破绽" }],
      },
      {
        id: "w_shuihu_wangdingliu",
        worldId: "w_shuihu",
        name: "王定六",
        nickname: "活闪婆",
        faction: "地煞",
        lore: "活闪婆王定六",
        fullLore: "活闪婆王定六",
        grade: "N",
        roleHint: "活闪婆",
        skills: [{ name: "活闪", description: "迅捷绕到侧翼" }],
      },
      {
        id: "w_shuihu_yubaosi",
        worldId: "w_shuihu",
        name: "郁保四",
        nickname: "险道神",
        faction: "地煞",
        lore: "捧帅字旗的险道神",
        fullLore: "捧帅字旗的险道神",
        grade: "N",
        roleHint: "险道神",
        skills: [{ name: "帅旗", description: "稳住己方军心" }],
      },
      {
        id: "w_shuihu_baisheng",
        worldId: "w_shuihu",
        name: "白胜",
        nickname: "白日鼠",
        faction: "地煞",
        lore: "黄泥冈下的白胜",
        fullLore: "黄泥冈下的白胜",
        grade: "R",
        roleHint: "白日鼠",
        skills: [{ name: "下药", description: "诱敌露出破绽" }],
      },
      {
        id: "w_shuihu_shiqian",
        worldId: "w_shuihu",
        name: "时迁",
        nickname: "鼓上蚤",
        faction: "地煞",
        lore: "能飞檐走壁的偷儿",
        fullLore: "能飞檐走壁的偷儿",
        grade: "SR",
        roleHint: "鼓上蚤",
        skills: [{ name: "盗甲", description: "夺取一场资源" }, { name: "走壁", description: "错位躲开一击" }],
      },
      {
        id: "w_shuihu_duanjingzhu",
        worldId: "w_shuihu",
        name: "段景住",
        nickname: "金毛犬",
        faction: "地煞",
        lore: "盗马的金毛犬",
        fullLore: "盗马的金毛犬",
        grade: "N",
        roleHint: "金毛犬",
        skills: [{ name: "盗马", description: "夺取一场资源" }],
      },
      {
        id: "w_shuihu_chaogai",
        worldId: "w_shuihu",
        name: "晁盖",
        nickname: "托塔天王",
        faction: "前任",
        lore: "劫生辰纲的东溪村主",
        fullLore: "劫生辰纲的东溪村主",
        grade: "SSR",
        roleHint: "托塔天王",
        skills: [{ name: "生辰纲", description: "诱敌露出破绽" }, { name: "聚义", description: "号召同伴并肩" }, { name: "曾头", description: "失手也能反制" }],
      }
    ],
  },
  {
    id: "w_liaozhai",
    title: "聊斋志异",
    genre: "CLASSICS",
    sourceHint: "蒲松龄",
    lore: "花妖狐魅入世，书生侠客夜遇奇缘",
    fullLore: "蒲松龄笔下的狐鬼花妖与人间交错：兰若寺、画皮、婴宁之笑、席方平告阴司。战场是夜巷、废寺、园林与冥司边缘。可写狐术、鬼影、剑客与科举冷暖，须守人情分寸，禁无敌不死、秒杀与现代武器。",
    canonHint: "狐魅、鬼影、剑客、人情；禁无敌秒杀与热兵器",
    coverKey: "liaozhai",
    official: true,
    presets: [
      {
        id: "w_liaozhai_niexiaoqian",
        worldId: "w_liaozhai",
        name: "聂小倩",
        nickname: "女鬼",
        faction: "鬼魅",
        lore: "兰若寺被迫摄魂的女鬼",
        fullLore: "金华女鬼受夜叉胁迫害旅人，遇宁采臣后改过，迁葬报恩。卡面写悔过与夜行，不写摄魂必杀。",
        grade: "SSR",
        roleHint: "女鬼",
        skills: [{ name: "剑气", description: "借燕侠剑袋护身" }, { name: "改过", description: "暂缓敌方杀意" }, { name: "夜行", description: "错位躲开一击" }],
      },
      {
        id: "w_liaozhai_ningcaichen",
        worldId: "w_liaozhai",
        name: "宁采臣",
        nickname: "宁生",
        faction: "书生侠客",
        lore: "不贪财色的方正书生",
        fullLore: "不贪财色的方正书生",
        grade: "SR",
        roleHint: "书生",
        skills: [{ name: "正气", description: "震慑动摇人心" }, { name: "拒金", description: "格挡一次诱惑" }],
      },
      {
        id: "w_liaozhai_yanchixia",
        worldId: "w_liaozhai",
        name: "燕赤霞",
        nickname: "燕侠",
        faction: "书生侠客",
        lore: "兰若寺外的仗剑客",
        fullLore: "兰若寺外的仗剑客",
        grade: "SSR",
        roleHint: "剑客",
        skills: [{ name: "剑袋", description: "克制鬼物攻势" }, { name: "夜巡", description: "探明潜藏杀机" }],
      },
      {
        id: "w_liaozhai_yingning",
        worldId: "w_liaozhai",
        name: "婴宁",
        nickname: "笑狐",
        faction: "狐魅",
        lore: "爱笑却不通礼法的狐女",
        fullLore: "鬼母所育狐女，常笑对俗礼。后入人间仍存野性。技能写笑与花，不写摄魂无敌。",
        grade: "SSR",
        roleHint: "狐女",
        skills: [{ name: "憨笑", description: "扰乱对手心神" }, { name: "花枝", description: "点破对方破绽" }, { name: "归山", description: "拉开交锋距离" }],
      },
      {
        id: "w_liaozhai_wangzifu",
        worldId: "w_liaozhai",
        name: "王子服",
        nickname: "王生",
        faction: "书生侠客",
        lore: "为婴宁入山的痴情书生",
        fullLore: "为婴宁入山的痴情书生",
        grade: "R",
        roleHint: "书生",
        skills: [{ name: "寻花", description: "点破一门路径" }],
      },
      {
        id: "w_liaozhai_qingfeng",
        worldId: "w_liaozhai",
        name: "青凤",
        nickname: "耿家狐",
        faction: "狐魅",
        lore: "患难中的谨慎狐女",
        fullLore: "患难中的谨慎狐女",
        grade: "SR",
        roleHint: "狐女",
        skills: [{ name: "避祸", description: "错位躲开一击" }, { name: "报恩", description: "协同强化攻势" }],
      },
      {
        id: "w_liaozhai_gengqubing",
        worldId: "w_liaozhai",
        name: "耿去病",
        nickname: "耿生",
        faction: "书生侠客",
        lore: "闯入狐宅的狂生",
        fullLore: "闯入狐宅的狂生",
        grade: "R",
        roleHint: "狂生",
        skills: [{ name: "闯宅", description: "突袭打断施法" }],
      },
      {
        id: "w_liaozhai_huapi",
        worldId: "w_liaozhai",
        name: "画皮女",
        nickname: "画皮",
        faction: "鬼魅",
        lore: "披美人皮的恶鬼",
        fullLore: "恶鬼绘人皮为美色惑人。道士识破后可收。技能写惑与裂，不写秒杀。",
        grade: "SR",
        roleHint: "恶鬼",
        skills: [{ name: "画皮", description: "扰乱对手心神" }, { name: "裂面", description: "撕开一次伪装" }],
      },
      {
        id: "w_liaozhai_wangsheng",
        worldId: "w_liaozhai",
        name: "王生",
        nickname: "太原王",
        faction: "书生侠客",
        lore: "惑于画皮的书生",
        fullLore: "惑于画皮的书生",
        grade: "N",
        roleHint: "书生",
        skills: [{ name: "贪色", description: "露出破绽受制" }],
      },
      {
        id: "w_liaozhai_daoshi",
        worldId: "w_liaozhai",
        name: "道士",
        nickname: "金华道",
        faction: "书生侠客",
        lore: "识破画皮的游方道人",
        fullLore: "识破画皮的游方道人",
        grade: "SR",
        roleHint: "道士",
        skills: [{ name: "葫芦", description: "收走一场鬼势" }, { name: "符水", description: "化解一次邪术" }],
      },
      {
        id: "w_liaozhai_jiaona",
        worldId: "w_liaozhai",
        name: "娇娜",
        nickname: "孔生狐",
        faction: "狐魅",
        lore: "善医的侠义狐女",
        fullLore: "善医的侠义狐女",
        grade: "SR",
        roleHint: "医狐",
        skills: [{ name: "疗伤", description: "调息稳住己方" }, { name: "除痈", description: "削弱对手根基" }],
      },
      {
        id: "w_liaozhai_lianxiang",
        worldId: "w_liaozhai",
        name: "莲香",
        nickname: "莲狐",
        faction: "狐魅",
        lore: "与鬼女争护书生的狐",
        fullLore: "与鬼女争护书生的狐",
        grade: "SR",
        roleHint: "狐女",
        skills: [{ name: "调息", description: "稳住己方气血" }, { name: "让情", description: "暂缓一场冲突" }],
      },
      {
        id: "w_liaozhai_lixiangui",
        worldId: "w_liaozhai",
        name: "李氏",
        nickname: "桑生鬼",
        faction: "鬼魅",
        lore: "与莲香共事的女鬼",
        fullLore: "与莲香共事的女鬼",
        grade: "R",
        roleHint: "女鬼",
        skills: [{ name: "冷香", description: "短暂迟滞对手" }],
      },
      {
        id: "w_liaozhai_hongyu",
        worldId: "w_liaozhai",
        name: "红玉",
        nickname: "冯家狐",
        faction: "狐魅",
        lore: "报恩复仇的侠狐",
        fullLore: "报恩复仇的侠狐",
        grade: "SR",
        roleHint: "侠狐",
        skills: [{ name: "夜刃", description: "突袭打断施法" }, { name: "抚孤", description: "稳住己方阵脚" }],
      },
      {
        id: "w_liaozhai_abao",
        worldId: "w_liaozhai",
        name: "阿宝",
        nickname: "孙生妻",
        faction: "凡人",
        lore: "使孙子楚痴情的富家女",
        fullLore: "使孙子楚痴情的富家女",
        grade: "R",
        roleHint: "凡人",
        skills: [{ name: "离魂", description: "错位躲开一击" }],
      },
      {
        id: "w_liaozhai_sunzichu",
        worldId: "w_liaozhai",
        name: "孙子楚",
        nickname: "孙生",
        faction: "书生侠客",
        lore: "为情可病可痴的书生",
        fullLore: "为情可病可痴的书生",
        grade: "R",
        roleHint: "痴生",
        skills: [{ name: "断枝", description: "以拙诚感化人心" }],
      },
      {
        id: "w_liaozhai_xifangping",
        worldId: "w_liaozhai",
        name: "席方平",
        nickname: "席生",
        faction: "书生侠客",
        lore: "告阴司的孝义少年",
        fullLore: "告阴司的孝义少年",
        grade: "SSR",
        roleHint: "讼鬼",
        skills: [{ name: "告状", description: "点破不公关键" }, { name: "忍刑", description: "格挡一次冲击" }, { name: "再告", description: "失手也能反制" }],
      },
      {
        id: "w_liaozhai_lupan",
        worldId: "w_liaozhai",
        name: "陆判",
        nickname: "朱生友",
        faction: "鬼魅",
        lore: "换心换头的判官",
        fullLore: "换心换头的判官",
        grade: "SR",
        roleHint: "判官",
        skills: [{ name: "换心", description: "调息稳住己方" }, { name: "朱笔", description: "点破战场关键" }],
      },
      {
        id: "w_liaozhai_xiaocui",
        worldId: "w_liaozhai",
        name: "小翠",
        nickname: "王太常狐",
        faction: "狐魅",
        lore: "装痴报恩的狐女",
        fullLore: "装痴报恩的狐女",
        grade: "SR",
        roleHint: "狐女",
        skills: [{ name: "装痴", description: "诱敌露出破绽" }, { name: "碎瓶", description: "扰乱对手判断" }],
      },
      {
        id: "w_liaozhai_xiangyu",
        worldId: "w_liaozhai",
        name: "香玉",
        nickname: "牡丹精",
        faction: "花妖",
        lore: "劳山下的牡丹花精",
        fullLore: "劳山下的牡丹花精",
        grade: "SR",
        roleHint: "花妖",
        skills: [{ name: "落瓣", description: "扰乱对手心神" }, { name: "再生", description: "调息稳住己方" }],
      },
      {
        id: "w_liaozhai_huangying",
        worldId: "w_liaozhai",
        name: "黄英",
        nickname: "菊精",
        faction: "花妖",
        lore: "能种菊养家的花精",
        fullLore: "能种菊养家的花精",
        grade: "R",
        roleHint: "花妖",
        skills: [{ name: "菊酒", description: "调息稳住己方" }],
      },
      {
        id: "w_liaozhai_gejin",
        worldId: "w_liaozhai",
        name: "葛巾",
        nickname: "牡丹",
        faction: "花妖",
        lore: "常大用所遇牡丹精",
        fullLore: "常大用所遇牡丹精",
        grade: "R",
        roleHint: "花妖",
        skills: [{ name: "国色", description: "扰乱对手心神" }],
      },
      {
        id: "w_liaozhai_xiaoxie",
        worldId: "w_liaozhai",
        name: "小谢",
        nickname: "陶生鬼",
        faction: "鬼魅",
        lore: "与秋容同学的女鬼",
        fullLore: "与秋容同学的女鬼",
        grade: "R",
        roleHint: "女鬼",
        skills: [{ name: "伴读", description: "加速己方节奏" }],
      },
      {
        id: "w_liaozhai_qiurong",
        worldId: "w_liaozhai",
        name: "秋容",
        nickname: "陶生鬼",
        faction: "鬼魅",
        lore: "废寺中的女鬼",
        fullLore: "废寺中的女鬼",
        grade: "R",
        roleHint: "女鬼",
        skills: [{ name: "闹学", description: "扰乱对手判断" }],
      },
      {
        id: "w_liaozhai_liancheng",
        worldId: "w_liaozhai",
        name: "连城",
        nickname: "乔生妻",
        faction: "凡人",
        lore: "以诗为聘的太守女",
        fullLore: "以诗为聘的太守女",
        grade: "R",
        roleHint: "凡人",
        skills: [{ name: "诗聘", description: "点破一门路径" }],
      },
      {
        id: "w_liaozhai_qiaosheng",
        worldId: "w_liaozhai",
        name: "乔生",
        nickname: "乔生",
        faction: "书生侠客",
        lore: "为连城割肉的义士",
        fullLore: "为连城割肉的义士",
        grade: "SR",
        roleHint: "义士",
        skills: [{ name: "割肉", description: "以伤换回生机" }],
      },
      {
        id: "w_liaozhai_huanniang",
        worldId: "w_liaozhai",
        name: "宦娘",
        nickname: "温生鬼",
        faction: "鬼魅",
        lore: "善琴的女鬼",
        fullLore: "善琴的女鬼",
        grade: "SR",
        roleHint: "琴鬼",
        skills: [{ name: "琴音", description: "扰乱对手心神" }, { name: "授曲", description: "强化友方节奏" }],
      },
      {
        id: "w_liaozhai_xin14",
        worldId: "w_liaozhai",
        name: "辛十四娘",
        nickname: "冯生狐",
        faction: "狐魅",
        lore: "能预祸的狐女",
        fullLore: "能预祸的狐女",
        grade: "SR",
        roleHint: "狐女",
        skills: [{ name: "预祸", description: "探明潜藏杀机" }, { name: "救狱", description: "暂缓一场冲突" }],
      },
      {
        id: "w_liaozhai_lvnvy",
        worldId: "w_liaozhai",
        name: "绿衣女",
        nickname: "蜂精",
        faction: "花妖",
        lore: "于生所遇绿衣蜂精",
        fullLore: "于生所遇绿衣蜂精",
        grade: "R",
        roleHint: "蜂精",
        skills: [{ name: "低唱", description: "扰乱对手心神" }],
      },
      {
        id: "w_liaozhai_zhuqing",
        worldId: "w_liaozhai",
        name: "竹青",
        nickname: "鱼容妻",
        faction: "花妖",
        lore: "乌衣国的鸦精",
        fullLore: "乌衣国的鸦精",
        grade: "R",
        roleHint: "鸦精",
        skills: [{ name: "飞羽", description: "拉开交锋距离" }],
      },
      {
        id: "w_liaozhai_pianpian",
        worldId: "w_liaozhai",
        name: "翩翩",
        nickname: "罗生仙",
        faction: "狐魅",
        lore: "山中剪叶为衣的仙女",
        fullLore: "山中剪叶为衣的仙女",
        grade: "SR",
        roleHint: "山仙",
        skills: [{ name: "剪叶", description: "虚势扰乱判断" }, { name: "涤垢", description: "化解一次邪术" }],
      },
      {
        id: "w_liaozhai_fengxian",
        worldId: "w_liaozhai",
        name: "凤仙",
        nickname: "刘生狐",
        faction: "狐魅",
        lore: "以镜诫夫的狐女",
        fullLore: "以镜诫夫的狐女",
        grade: "R",
        roleHint: "狐女",
        skills: [{ name: "镜诫", description: "点破对方破绽" }],
      },
      {
        id: "w_liaozhai_ruiyun",
        worldId: "w_liaozhai",
        name: "瑞云",
        nickname: "贺生妻",
        faction: "凡人",
        lore: "面斑后见真情的名妓",
        fullLore: "面斑后见真情的名妓",
        grade: "R",
        roleHint: "凡人",
        skills: [{ name: "真赏", description: "感化动摇人心" }],
      },
      {
        id: "w_liaozhai_cuxi",
        worldId: "w_liaozhai",
        name: "促织童",
        nickname: "成名子",
        faction: "凡人",
        lore: "化促织的农家儿",
        fullLore: "化促织的农家儿",
        grade: "N",
        roleHint: "促织",
        skills: [{ name: "争斗", description: "以小搏大一击" }],
      },
      {
        id: "w_liaozhai_laoshan",
        worldId: "w_liaozhai",
        name: "劳山道士",
        nickname: "王生师",
        faction: "书生侠客",
        lore: "授穿墙却戒心的道士",
        fullLore: "授穿墙却戒心的道士",
        grade: "R",
        roleHint: "道士",
        skills: [{ name: "穿墙", description: "错位躲开一击" }],
      },
      {
        id: "w_liaozhai_huabi",
        worldId: "w_liaozhai",
        name: "画壁仙",
        nickname: "壁上女",
        faction: "花妖",
        lore: "朱孝廉走入画中的仙",
        fullLore: "朱孝廉走入画中的仙",
        grade: "R",
        roleHint: "画仙",
        skills: [{ name: "入画", description: "错位躲开一击" }],
      },
      {
        id: "w_liaozhai_tianqilang",
        worldId: "w_liaozhai",
        name: "田七郎",
        nickname: "猎户",
        faction: "书生侠客",
        lore: "报恩复仇的猎户",
        fullLore: "报恩复仇的猎户",
        grade: "SR",
        roleHint: "侠客",
        skills: [{ name: "报恩", description: "协同强化攻势" }, { name: "夜刃", description: "突袭打断施法" }],
      },
      {
        id: "w_liaozhai_xiaomei",
        worldId: "w_liaozhai",
        name: "小梅",
        nickname: "林生妾",
        faction: "狐魅",
        lore: "保孤兴家的狐女",
        fullLore: "保孤兴家的狐女",
        grade: "R",
        roleHint: "狐女",
        skills: [{ name: "保孤", description: "稳住己方阵脚" }],
      },
      {
        id: "w_liaozhai_aoying",
        worldId: "w_liaozhai",
        name: "阿英",
        nickname: "鹦鹉",
        faction: "花妖",
        lore: "甘生所遇鹦鹉精",
        fullLore: "甘生所遇鹦鹉精",
        grade: "N",
        roleHint: "禽精",
        skills: [{ name: "学语", description: "扰乱对手判断" }],
      }
    ],
  },
]
